### ISSUE TITLE
Static Aircraft

### ISSUE THREAD

**Issue by Elias413** [skiselkov/BetterPushbackC#1]
There is an issue with engaging the pushback, one you call for pushback, all of the Static Aircraft dissapear.
I assume this is to get rid of the stock pushback cars from X-Plane 11, but it definitely puts a hamper on the realism with the static aircraft.

By the way, this is the greatest plugin I have ever installed.

**Comment by skiselkov** [comment]
This is a bug and I believe I've got a fix for it. I'll close this issue once the fix is pushed.

**Comment by skiselkov** [comment]
Please try the latest build to see if it fixes the problem.

**Comment by Elias413** [comment]
@skiselkov It is fixed with this latest build. Thanks for your amazing work, I will post any other bugs I find, if any!

**Comment by skiselkov** [comment]
Thanks for reporting and please do keep testing.
