### ISSUE TITLE
X-Plane 10 Crash

### ISSUE THREAD

**Issue by Billytreiah** [skiselkov/BetterPushbackC#10]
Good Day. I'm using Win 7 64Bit and X-Plane 10.51, when i was flying the IXEG V1.2 and finished my pushback, when the car wanted to go away X-Plane 10 Crashed :( 
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1150955/Log.txt)

**Comment by skiselkov** [comment]
Thanks for the report. The initial & final tug route planning need some reworking as they're just too unstable right now. I should have a fix by the end of today.

**Comment by skiselkov** [comment]
Please try with the v0.12 build, it contains fixes that should help address stability of the tug driving logic.
