### ISSUE TITLE
No more bip bip sound

### ISSUE THREAD

**Issue by fregate083** [skiselkov/BetterPushbackC#102]
Hi,

for last updates, no more sounds (bip bip bip) as the tugmaster comes and during operations

Also , cab ask "set parking brakes" altough it is already st on

Thanks for all this beautiful works

Regards

**Comment by skiselkov** [comment]
These appear like two problems:
1. lack of sounds from tug: verify that you don't have Exterior and Interior sound volume set low
2. "set parking brakes" with parking brakes on: which aircraft are you using and please also provide a Log.txt so I can identify the BP version you're running.

**Comment by fregate083** [comment]
Hi,
Thanks a lot for your reply
1) Sound is OK at maximum exterior and interior, I checked
2) I use  X-Plane 10.51r2 (build 105101 64-bit)

A320 JAR DESIGN 2.7 r1 with your latest update BP  v 0.41

2017-08-14 10:06:01 BetterPushback[xplane.c:386]: This is BetterPushback-8fd01d8 libacfutils-b415bd1
Loaded: S:\X-Plane 10/Resources/plugins/BetterPushback/64/win.xpl (skiselkov.BetterPushback).
Ground Handling Plugin by JARDesign v.200317 for X-Plane 10/11
Loaded: S:\X-Plane 10/Resources/plugins/GndHandling/win.xpl (jardesign.crew.ground.handling).

Loaded: S:\X-Plane 10/Resources/plugins/RealWeatherConnector/64/win.xpl (Sundog.MetarBridge).

Loaded: S:\X-Plane 10/Resources/plugins/SeaTraffic/64/win.xpl (Marginal.SeaTraffic).

Loaded: S:\X-Plane 10/Resources/plugins/SilverLining/64/win.xpl (SilverLiningV4.Clouds).

SoundMaxx: Installed upgraded sounds.
Loaded: S:\X-Plane 10/Resources/plugins/SoundMaxx/64/win.xpl (maxxxp.soundmaxx).

X-Life plugin by JARDesign Ver.2.0 r4 250717
XL: 0 : UUID=898fc2f5-2be6-45d3-90e6-32d8ac51b909
XL: 0 : JARDesign plugin: S:\X-Plane 10\Resources\plugins\X-Life\Airports/airports.txt file updated.
Loaded: S:\X-Plane 10/Resources/plugins/X-Life/win.xpl (jardesign.x-life).

Loaded: S:\X-Plane 10/Resources/plugins/XPUIPC/64/win.xpl (XPUIPC/XPWideFS.).

FILE OK.
Loaded: S:\X-Plane 10/Resources/plugins/iTow/64/win.xpl (jardesign.crew (C)).
Fetching plugins for Custom Scenery/Aerosoft LSZH Airport Zurich V2.0 a/plugins

Loaded: Custom Scenery/Aerosoft LSZH Airport Zurich V2.0 a/plugins/GroundTraffic/64/win.xpl (Marginal.GroundTraffic.Aerosoft LSZH Airport Zurich V2.0 a).

Custom Scenery/Aerosoft LSZH Airport Zurich V2.0 a/plugins/xdatarefs/X-DataRefs_Config.txt
Custom Scenery/Aerosoft LSZH Airport Zurich V2.0 a/plugins/xdatarefs/X-DataRefs_License_Key.txt 

    Le Lundi 14 août 2017 16h30, Saso Kiselkov <notifications@github.com> a écrit :
 

 These appear like two problems:   
   - lack of sounds from tug: verify that you don't have Exterior and Interior sound volume set low
   - "set parking brakes" with parking brakes on: which aircraft are you using and please also provide a Log.txt so I can identify the BP version you're running.

**Comment by skiselkov** [comment]
> 1) Sound is OK at maximum exterior and interior, I checked

Please clarify: did you mean you've resolved the problem? Or that your sound volume is maximum and you still can't hear BP?

> A320 JAR DESIGN 2.7 r1

Unfortunately I don't have the JAR A320. I know some folks who can test it though, I'll ask them to try to reproduce this. What's strange is you didn't report that BP wouldn't be able to push when it asks for the parking brake to be released - that's what I would expect when the parking brake position detection doesn't work (since it uses the exact same code).

**Comment by fregate083** [comment]
1) No sorry, I mean the sound volume is at maximum and I can't still hear the bip bip sound. The others sounds I hear that. But with older version of BP I had the bip bip sound

2)Pushback are made; I switch shortly in position off an on

**Comment by fregate083** [comment]
Hi, concerning my 2 reports :
-1) its ok again with your latest update from the last night
2) all is ok; pushback are well made. Its perhaps more on the syntax 
I'm not a professionnal pilot or tugmaster. But instead to tell "set parking brakes" why not tell "check if brakes are set" ?

Thansk for all

regards

Alexandre

**Comment by skiselkov** [comment]
Glad to hear it's fixed.
The "set parking brake" is a standard call and used commonly in real world communications.

**Comment by fregate083** [comment]
Hi,
After several tests I understodd why I didn't hear the bip bip sound when tugmaster levelled the gear of the plane.
I use the DHL VIrtual Group Smart Cars modul (from TDFI) and it contents some sounds with pilot announces, stewards and so on..
When I used it no bip bip sound otherwile it's OK.

Also surely audio channel conflict ?

Is it possible to see on which chanel the sound is problematic ?

Thanks a lot for your help

PS : perhaps other pilots are in the same situation ?

Regards

Alexandre
