### ISSUE TITLE
VIenna Airport Livery AST-3F

### ISSUE THREAD

**Issue by fregate083** [skiselkov/BetterPushbackC#103]
Hi,

After talking with liebbe10, I re open a post because I met some bugs with the livery
See photo

-a kind of black rectangle under the tug engine
-window are not transparent but opaque grey

Xplane 10.51 r1 and JAR DESIGN 2.7

Regards
![bp at loww](https://user-images.githubusercontent.com/30977163/29312316-0a872448-81b5-11e7-8520-f84ee2bdaf39.jpg)

**Comment by skiselkov** [comment]
Fixed in v0.43, please test.

**Comment by fregate083** [comment]
Hi skiselkov,

Very good work with your latest updates :)) its amazing !
All is ok no more grey window and no more black rectangle

It would be also great (but I know it depends from other devs) that it comes tug liveries for Air France, British Airways, Alitalia and so on..

Thanks so much for all your work

Regards

Alexandre
