### ISSUE TITLE
explanation of liveries

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#104]
Hey
Would it be possible to make some sort of paint kit were there is a layer that shows what part of the truck is what in the livery file. I tried to paint the ast-1x but it is hard to guess what could be what...Especially for placing logos

Greetings Ben

**Comment by skiselkov** [comment]
You shouldn't be painting onto the PNGs, they aren't really suitable for that. What you want is the Gimp XCF originals, present in `objects/src/<tugname>`, with the UV layout in it and each object in its own layer to help identify what's what.
As for painting the AST-1X, I'd recommend against that so far. I still have some major modeling and texturing work that needs to be done there, so your paint would be obsolete within a few days.
For an explanation of how the livery auto-selection engine works, please see https://github.com/skiselkov/BetterPushbackC/blob/master/objects/tugs/LIVERIES_HOWTO.txt
