### ISSUE TITLE
Wing clearance lines

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#105]
Saso,
what do you think about adding lines (at list as an option) to indicate the wing clearance of the aircraft. 
I would expect this to be doable since they can be aligned to the blue centerline of the pushback?
Please see the pictures for clarification.

![bildschirmfoto 2017-08-10 um 13 53 11](https://user-images.githubusercontent.com/17392829/29360780-cf667eb0-8284-11e7-8f4e-6f5cd37ae5dd.png)
![bildschirmfoto 2017-08-10 um 13 52 26](https://user-images.githubusercontent.com/17392829/29360781-cf8bed08-8284-11e7-89c5-571ba1df1e2d.png)
![bildschirmfoto 2017-08-10 um 13 43 13](https://user-images.githubusercontent.com/17392829/29360782-cf8cabee-8284-11e7-987f-c9b52594e1ca.png)

**Comment by skiselkov** [comment]
Not a bad idea and it's not that difficult from a coding standpoint. The hard part is getting the wingtip position information from X-Plane. Unfortunately, this isn't easily accessible, as it is part of the plane 3D model information. I'll think about it some and see what I can come up with.

**Comment by JoseBDA** [comment]
X-plane aleady classifies the aircraft in sizes, which ae used by airport traffic control to assign gates and taxiways; that information is available from the acf file and I can look it up if you wish.

**Comment by xplana** [comment]
i think the classification is not that helpful. 
if there is a chance to get the real wingspan of the aircraft out of its data and stretch your icons wings according to the kingsize, that would be of help. Drawing then the outer clearance lines would be helpful to see wether you hit some obstacles while pushing back (trucks, floodlights…)

**Comment by skiselkov** [comment]
@JoseBDA Please do.

**Comment by xplana** [comment]
How about determining the wing span from the position of the respective aircraft lights. I know this is not the cleanest way of doing it but it maybe works!?

**Comment by JoseBDA** [comment]
OK. The wing semi-length is encoded in the acf file; for the default B737-800 I read: 
P _wing/8/_semilen_SEG 18.850000381
I hope it helps.

**Comment by skiselkov** [comment]
Yeah, that's what I'm looking at right now (as well as body radii to paint an accurate fuselage outline).

**Comment by xplana** [comment]
Yo are great gentleman

**Comment by skiselkov** [comment]
Feature is implemented, please test with as many aircraft as possible. If the aircraft outline doesn't show up right, please attach a screenshot and the .acf file of the affected aircraft.
The attachment here isn't a full plugin build, only the binaries. Please replace the `.xpl` files in `64` with the ones in this file.
[64.zip](https://github.com/skiselkov/BetterPushbackC/files/1229943/64.zip)

**Comment by xplana** [comment]
this is looking quite good, although there are some things i noticed. 

1) changing size of the shape/outline depending of zoom-level in planing mode. 
The size of the shape (wing-span) currently changes, depending of the choosen zoom level. If you zoom in the outline/shape gets smaller compared to the wingspan. If you zoom out a lot, the adaption of the shape/outline gets better and closer to the real wingspan/size of the fuselage. 
Checkout the video, especially at the end you are going to visually notice what i am talking about:

[https://youtu.be/hNnDsAUOWRg](url)

2) Winglets not considered
It seems as if your algorithm does not include aircraft winglets at all.I am not sure about that but i can imagine them only to be part of the 3D model. 
With respect to the wingspan, they are significant. I wish i had an idea of how to do that..

![bildschirmfoto 2017-08-17 um 10 22 29](https://user-images.githubusercontent.com/17392829/29404957-cd084aaa-833c-11e7-93ac-84d2571f4f6a.png)

3) Layout adaption error
While all tested aircraft return a plausible shape/outline, only the EMB110 by dreamfoillabs returns some weird result. See here:

![bildschirmfoto 2017-08-17 um 10 05 37](https://user-images.githubusercontent.com/17392829/29404735-1e37657e-833c-11e7-8cb7-21580d93c697.png)
[EMB110.acf.zip](https://github.com/skiselkov/BetterPushbackC/files/1230720/EMB110.acf.zip)

4) Shape/Outline deviations
Signifficant deviation with respect to the elevator but not a real problem  (default  Baron)

![bildschirmfoto 2017-08-17 um 10 34 04](https://user-images.githubusercontent.com/17392829/29405211-960dd000-833d-11e7-8b09-9b5ebb43957e.png)

5) Lines
I am sure there is some more refinement planned, but i´ll put that on the list here as well.

![bildschirmfoto 2017-08-17 um 10 22 32](https://user-images.githubusercontent.com/17392829/29405432-3286740a-833e-11e7-88be-e1f816588428.png)


Beside that, the approach you have started looks very promising and it seems a good addition to the plugin!

**Comment by andreynovikov** [comment]
@skiselkov I wish Laminar Research will hire you for a full time job!

**Comment by skiselkov** [comment]
@xplana 
> changing size of the shape/outline depending of zoom-level in planing mode.

It actually doesn't. What you are seeing is perspective distortion. The aircraft symbol is sitting on the ground, but your aircraft's wings aren't. Set the sun to be overhead and compare the aircraft symbol to the aircraft's shadow - you'll see they overlap perfectly.

> Winglets not considered

The aircraft symbol is derived from the aerodynamic model, not the visual one, so if the aircraft has optional winglets that aren't part of the aerodynamic model, then they won't show up (the 757's winglets are like they - they don't work, they're just there for show).

> Layout adaption error

Will debug, thanks. The EMB110 must be doing something weird with respect to object origin placement.

> Shape/Outline deviations

Again, the outline is based on the aerodynamic model, not the visual one. Unfortunately this isn't something I can fix.

> I am sure there is some more refinement planned, but i´ll put that on the list here as well.

Yep, I'll refine this. Right now the lateral line placement is based on the declared wingspan of the aircraft, but without taking wing sweep into account. I'll modify this to take the longitudinal displacement of the wing tip chord line into account.

**Comment by xplana** [comment]
> changing size of the shape/outline depending of zoom-level in planing mode.
>>It actually doesn't. What you are seeing is perspective distortion. The aircraft symbol is sitting on the ground, but your aircraft's wings aren't. Set the sun to be overhead and compare the aircraft symbol to the aircraft's shadow - you'll see they overlap perfectly.

I don´t think I get this. I send some more pictures from different zoom levels in the planning mode. You can see that the shape size looks way different. I don't see a perspective related thing here because every picture should be taken from a (more or less) 90° angle

![bildschirmfoto 2017-08-17 um 16 48 18](https://user-images.githubusercontent.com/17392829/29418398-7b67a6ca-836c-11e7-9f44-f8008ecbe064.png)
![bildschirmfoto 2017-08-17 um 16 48 28](https://user-images.githubusercontent.com/17392829/29418399-7b8d38cc-836c-11e7-9fbe-d8d5900b6191.png)
![bildschirmfoto 2017-08-17 um 16 51 23](https://user-images.githubusercontent.com/17392829/29418401-7b952604-836c-11e7-975d-cd647e9185c5.png)
![bildschirmfoto 2017-08-17 um 16 52 09](https://user-images.githubusercontent.com/17392829/29418400-7b8d1c20-836c-11e7-998b-f1cc12507cb3.png)

**Comment by skiselkov** [comment]
This is what I'm talking about. In this image I have the sun almost directly overhead and you can see that the aircraft outline almost perfectly copies the shadow being cast by the aircraft.
![shot](https://user-images.githubusercontent.com/3300688/29426032-9d805b76-8385-11e7-962b-6abb892868eb.png)
Just because you are overhead, doesn't mean that perspective no longer applies. The overhead view is NOT isometric.

**Comment by skiselkov** [comment]
Implemented in v0.43, please test. EMB110 model problem should also be fixed.

**Comment by xplana** [comment]
I slowly understand your point with the perspective distortion, it just feels somewhat strange - but i see this is not the plugins point but the overall presentation method in xpl.

The new shape/outline looks way better. I just noticed that on the tail of some aircraft, there still are little overlaps. Please see here:

![bildschirmfoto 2017-08-18 um 11 50 03](https://user-images.githubusercontent.com/17392829/29453918-a1e512e8-840b-11e7-82e3-4a34aae4084f.png)
 
Another thing that i have noticed are this things. Not sure if they are supposed to be that way?!

![bildschirmfoto 2017-08-18 um 11 53 47](https://user-images.githubusercontent.com/17392829/29454222-a10f8fb4-840c-11e7-8e7a-3e2def32c6eb.png)

I hope my pettiness does not drive you crazy :)

**Comment by skiselkov** [comment]
@xplana 
> The new shape/outline looks way better. I just noticed that on the tail of some aircraft, there still are little overlaps.

This is how the aerodynamic model positions the wings, so that's how we paint them. But I guess we could massage the outline model to place the wings on the outside of the fuselage outline. Let me think about this.

> Another thing that i have noticed are this things. Not sure if they are supposed to be that way?!

That is indeed the correct path the wingtips on a swept-back wing will paint when the aircraft spins around its main landing gear. This is because the wingtip is displaced rearward from the main landing gear, so it will naturally paint a "wavy" pattern in turns.

**Comment by skiselkov** [comment]
This is what I was talking about when I said "displaced rearward":
![shot](https://user-images.githubusercontent.com/3300688/29455355-2ab95a70-8411-11e7-9fc0-72c145cc2d08.png)

**Comment by xplana** [comment]
ok, got it. Good point(s).
And as I said, hope I am not about driving you crazy :)

**Comment by skiselkov** [comment]
>  And as I said, hope I am not about driving you crazy :)

No worries.

**Comment by AirLuSa** [comment]
Perfect implication. Looks really cool and working nice. Tested it with the x737 by EADT will test other aircraft soon.

**Comment by skiselkov** [comment]
Closing as implemented.
