### ISSUE TITLE
not compatible with SSG E-170 Evolution

### ISSUE THREAD

**Issue by Matt7377** [skiselkov/BetterPushbackC#106]
I have found that the plugin does not work with the SSG E-170 Evolution. An update with compatability for this aircraft would be greatly appriciated.

**Comment by skiselkov** [comment]
I don't have this aircraft. Can you please describe what kind of incompatibility is taking place? What's not working, or in what way is it behaving badly? A video would be best, as that usually contains clues that might help me.

**Comment by Matt7377** [comment]
It is doing the same thing that it did to the zibo 737 before that was fixed. When it goes to turn the aircraft it turns to sharply and spins it in circles over and over again.

**Comment by skiselkov** [comment]
Can you verify that you don't have your nosewheel steering disabled and/or hydraulics pressurized during pushback?

**Comment by skiselkov** [comment]
Closing as "on hold" until submitter responds.
