### ISSUE TITLE
Switching aircraft in planner doesn't properly re-enable menu items

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#108]
while testing the outline shapes, i switched between the aircraft (even while in top-down planing view of better pushback) and x-plane crashed. 

Please see attached log file.

[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1230682/Log.txt)

**Comment by skiselkov** [comment]
Bug found, will be fixed in next release.

**Comment by xplana** [comment]
thx

**Comment by skiselkov** [comment]
Please don't close issues yourself, I will do it once the fix is in the build.

**Comment by xplana** [comment]
sure

**Comment by skiselkov** [comment]
Fixed in v0.43, please test.

**Comment by xplana** [comment]
works great

**Comment by xplana** [comment]
No more crashes!
But there seems to be a bug left. 

If i switch the aircraft while i am in planning mode, the new loaded plane will by default show the cockpit view and there seems no way back to the planing mode. 

If i then try to leave the planning view via the menu, nothing happens. So there is some loop you can't get out of. 

![bildschirmfoto 2017-08-18 um 10 35 12](https://user-images.githubusercontent.com/17392829/29451053-82d9a620-8401-11e7-9a0d-963a13eb80ce.png)

**Comment by skiselkov** [comment]
Fixed in v0.44, please test.

**Comment by xplana** [comment]
Working fine!

**Comment by skiselkov** [comment]
Thanks for testing
