### ISSUE TITLE
Optional view/camera perspective while pushback?

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#109]
soso, this is the least important feature request but i think quite an entertaining one. 
Is there a chance to get a way to change the current (view/camera) perspective while pushing back 
to something similar to that? 

![bildschirmfoto 2017-08-17 um 17 07 41](https://user-images.githubusercontent.com/17392829/29419150-a442c0c8-836e-11e7-8cf4-0873de9fc4a4.png)

**Comment by skiselkov** [comment]
I actually already had this planned, so yeah, it's definitely going in.

**Comment by xplana** [comment]
Free for testing :)

**Comment by skiselkov** [comment]
@xplana Yeah, it's a little rough around the edges so far, so I still want to make some improvements to it. However, if you feel adventurous, feel free to use the attached build.
[64.zip](https://github.com/skiselkov/BetterPushbackC/files/1241996/64.zip)
To move the view around, use your LEFT mouse button to click & drag. All your other normal view controls will also work (key binds & joystick buttons). To come out of the tug view, simply select any other view in the usual manner (recall a stored view via the numpad, "View" menu, Shift-number selection, etc.).

**Comment by xplana** [comment]
thanks saso,
ill give it a try. 
is there a mail address i can contact you ?

**Comment by xplana** [comment]
soso, how do i switch to the new perspective/view? Don’t see a button or menu item?

**Comment by skiselkov** [comment]
Should be in the BetterPushback plugin menu - "Tug cab view". It will enable once you start the pushback operation.

**Comment by xplana** [comment]
not there,
see here while pushback running

**Comment by skiselkov** [comment]
Maybe I sent you the wrong build, I'll check.

**Comment by skiselkov** [comment]
No it's definitely the correct build. You DID place it into the installed plugin and replaced the contents of the `64` folder, right? This isn't a full plugin build.

**Comment by skiselkov** [comment]
@xplana I can't see any image attachments in the comments, github removes them when using e-mail responses. Can you try to use the Github comments GUI to attach it? Alternatively, e-mail me directly, you should be able to see my e-mail address under my profile if you're logged into Github.

**Comment by xplana** [comment]
sorry for that, it´s working, i might not have overwritten the files the first time. 
the way it saves the perspective/view is great
would be fun to be able to save the view onto one of the view shortcuts of x-plane?
it would also be fun to be able to cycle between 2 or more views (tug cockpit, the walking officers perspective next to the tug.. :)
great stuff, very nice done

**Comment by xplana** [comment]
https://youtu.be/VKjMfqXL97o

**Comment by skiselkov** [comment]
> would be fun to be able to save the view onto one of the view shortcuts of x-plane?

You can achieve that by simply mapping a key bind or joystick button to the `BetterPushback/cab_camera`. The view position is reset when the pushback operation is completed or when starting a new flight. I might implement persistent tug camera positioning before releasing this, haven't decided yet.

**Comment by xplana** [comment]
![bildschirmfoto 2017-08-23 um 02 16 44](https://user-images.githubusercontent.com/17392829/29612853-9e835c76-8803-11e7-993b-285fe10ffe3c.png)

**Comment by skiselkov** [comment]
@xplana Yep, that's what it looks like when you blind the driver.

**Comment by xplana** [comment]
it already hurts :)

**Comment by skiselkov** [comment]
Feature implemented in v0.44. Thanks for the suggestion!
