### ISSUE TITLE
Plan path when tug connected

### ISSUE THREAD

**Issue by SinusJayCee** [skiselkov/BetterPushbackC#11]
First of all, this is a really nice plugin! 

I've a feature request: It would be nice, if the pushback path could be planned when the tug is already connected. When flying online, one get the pushback direction together with the clearance for pushback. However, I prefer to have to tug already connected when requesting the clearance in order to waste no time.

Thank you in advanced!

**Comment by skiselkov** [comment]
I'll see if I can somehow get this into the next alpha build.

**Comment by skiselkov** [comment]
Currently working on AST-1X tug model. I'll return to this after that is done.

**Comment by SinusJayCee** [comment]
All right! I'm waiting for a tug for wide-body airliners as well and this feature is probably more important, since it's required by more people.

**Comment by skiselkov** [comment]
Here's a super-quick render in case you're interested in seeing progress.
![ast-1x](https://user-images.githubusercontent.com/3300688/28380098-5695736c-6cb6-11e7-872c-9ea2085b2083.png)

**Comment by SinusJayCee** [comment]
Looks really nice already! Can't wait to try it. You may want to start a thread on the x-plane.org forum. I guess many people there are interested in following the progress of your development.

Btw: Are you planning to add the 3-axes version of the AST-1X later as well? It's rarely used in reality, but it's in very interesting vehicle.

**Comment by skiselkov** [comment]
Feature is implemented in v0.19. Simply select "Connect first" from the pushback planner. This closes the planner and the tug drives up and connects. Then when you are ready, simply hit "Start pushback" and the planner comes up again and asks for directions. With the route entered and confirmed, the pushback starts immediately. Please test.

> You may want to start a thread on the x-plane.org forum

I don't know, not a big fan of reading through hundreds of pages of forum posts like Zibo. I'll see about that though as I get closer to a 1.0.

> Btw: Are you planning to add the 3-axes version of the AST-1X later as well? It's rarely used in reality, but it's in very interesting vehicle.

Been thinking about that. It's not too difficult to model from the AST-1X I have right now, they're actually really quite similar, but it's lower priority right now. As you correctly noted, they're rare. I think they only sold like three units total and they're all at Frankfurt.

**Comment by SinusJayCee** [comment]
Thanks for implementing the feature! Unfortunately, I can't test it this weekend. I will test it as soon as possible at the beginning of the next week.

> I don't know, not a big fan of reading through hundreds of pages of forum posts like Zibo. I'll see about that though as I get closer to a 1.0.

I totally agree with this. In addition, I guess it's a good idea in general to announce something short before it's finished, but not earlier.

> Been thinking about that. It's not too difficult to model from the AST-1X I have right now, they're actually really quite similar, but it's lower priority right now. As you correctly noted, they're rare. I think they only sold like three units total and they're all at Frankfurt.

I've read about two additional 3-axes AST-1X at the Airbus factory in Hamburg Finkenwerder and one in China. But this is still very rare. So it's definitely not an important feature.

**Comment by nriddell** [comment]
I've been able to test this fix a few times and is working perfectly for me. Have tried with IXEG733, default B747. Please let me know if there is anything specific you want me to report to help you close this one.

**Comment by SinusJayCee** [comment]
I just tested the new feature. Works perfectly for me as well. I also tried the new AST-1X with the JAR A330, which also works perfectly.

I will know start to regularly use the plugin and will inform you if I may find something that doesn't work as intended. But for know I'm completely satisfied. Many thanks for the quick implementation!

**Comment by skiselkov** [comment]
Thanks for the confirmation.
