### ISSUE TITLE
Zibo last version 3.06h

### ISSUE THREAD

**Issue by alessandro61** [skiselkov/BetterPushbackC#110]
Hello,

I have issue with your last pushback version and zibo 3.06h.
Here log.txt
Thanks and regards.
Alessandro
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1233895/Log.txt)

**Comment by skiselkov** [comment]
Please describe the issue, because the Log file doesn't tell me.

**Comment by alessandro61** [comment]
Ok.
Two screenshots. PB never stops with engines on. May be Zibo problem.

**Comment by skiselkov** [comment]
You didn't attach any screenshots.

**Comment by skiselkov** [comment]
Please record a video. I just tested with 3.06h and cannot reproduce any problem.

**Comment by beattleboy** [comment]
I just tested with 3.06h and .43...   I got no issues as well.  Worked very nicely I might add.

**Comment by skiselkov** [comment]
Ok, closing

**Comment by alessandro61** [comment]
Hi,

Problem and issue solved! Thanks and regards!!
Alessandro 

Inviato da iPhone

**Comment by skiselkov** [comment]
@alessandro61 Can you please detail what you did to resolve the issue? Maybe I can automate the process in future releases.

**Comment by alessandro61** [comment]
It is quite common to play new update without reading release notes. In my case, I have switched on taxi lignts during PB, ruining driver's eyesight. That's reason...I guess. Aircraft begins to move  around as crazy.
Btw, I appreciate very much your PB.
Alessandro

Inviato da iPhone
