### ISSUE TITLE
Microsoft Visual C++ Runtime Library

### ISSUE THREAD

**Issue by notam9** [skiselkov/BetterPushbackC#111]
Error right before the tractor connect to the main gear: "This application has requested the runtime to terminate it in an unusual way"

**Comment by skiselkov** [comment]
Can you please attach your `Log.txt`.

**Comment by Nus71** [comment]
Hi, just the same thing happened to me. Just before connecting the pusch the same error has come out. 
Thank you for taking time in it.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1242968/Log.txt)

**Comment by skiselkov** [comment]
@Nus71 This is caused by a change in Zibo's 737. The latest one should contain a fix. I'll be pushing a fix to BP soon as well, which takes care of this from BP's end.

**Comment by Nus71** [comment]
as always thank you very much! Skiselkov

**Comment by skiselkov** [comment]
Fixed in v0.44, please test.

**Comment by skiselkov** [comment]
Closing as dup of #111, which was fixed.
