### ISSUE TITLE
AirFrance Livery AST-3F

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#113]
I made a livery for Air France and in general french airports.
[AirFrance.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1235814/AirFrance.livery.zip)

**Comment by liebbe10** [comment]
Oh sorry...will export a new version in the evening :) 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by skiselkov** [comment]
Thanks!

**Comment by liebbe10** [comment]
![ast-3f_tex](https://user-images.githubusercontent.com/30324171/29694138-35fd0930-893a-11e7-9baa-eeda03198a07.png)
This should be the correct version

**Comment by skiselkov** [comment]
Added, but could you please specify a tighter list of airports rather than just "anything in France"?

**Comment by liebbe10** [comment]
I don't have a list about France but I think it wont look wrong or unrealistic if an Air France tug will serve you at any airport located in France?!

**Comment by skiselkov** [comment]
Closing as implemented.
