### ISSUE TITLE
Pausing Pushback?

### ISSUE THREAD

**Issue by Milki52** [skiselkov/BetterPushbackC#115]
Hey, as atc i often come to situations where i have to cancel or break some Pushs during traffic that uses wrong taxiways or something else. Is there a possibilty to add that feature? Like when you set the Parkingbrake back to on? 

Thanks :)

**Comment by skiselkov** [comment]
Have you tried to just push down on the aircraft brakes or setting the parking brake? It should do exactly what you ask: pause the pushback. Once you let go, it will resume. Or if you don't want to resume, just select "Stop Pushback" from the plugin's menu.
If any of this is not working for you, then that's a bug I need to fix.

**Comment by Milki52** [comment]
last time i tried it at Frankfurt during pushback because the ivao controller told me to do that, but it doesnt work. I can try it again :)

**Comment by skiselkov** [comment]
Have you had time to try this again?

**Comment by skiselkov** [comment]
Closing as submitter unresponsive.
