### ISSUE TITLE
British Airways livery AST-3F

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#116]
I made a livery for British Airways and in for UK airports.
<img width="1680" alt="bildschirmfoto 2017-08-19 um 18 04 08" src="https://user-images.githubusercontent.com/30324171/29488368-919dadce-8509-11e7-93bb-14cabbbe9b0f.png">
[BritishAirways.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1236484/BritishAirways.livery.zip)

**Comment by skiselkov** [comment]
Included in v0.44.
