### ISSUE TITLE
Will not turn.

### ISSUE THREAD

**Issue by Britton757** [skiselkov/BetterPushbackC#119]
Little issue here, it works wonderfully and pushes BACK great. The problem is that it will not turn, when it is time to turn, it just shakes and goes very very slow. Kinda sucks I can not use this program due to this issue.

**Comment by skiselkov** [comment]
Please **always** provide your `Log.txt` with a bugreport, it helps me figure out which sim version, OS and aircraft combo you are using. If by any chance you are running the FlightFactor 757v2 or 767, please make sure you are updated to the latest versions from 2 weeks ago, as they contain a necessary compatibility fix that resolves a "no turn" issue.

**Comment by skiselkov** [comment]
Closing as submitter unresponsive.
