### ISSUE TITLE
Radius of rotation limit

### ISSUE THREAD

**Issue by Devirex** [skiselkov/BetterPushbackC#121]
Hi,

could you implement a feature in planner which don't let you choose a too small rotation radius which is can't be performend by an aircraft or the tug. 

Thanks in advance

**Comment by skiselkov** [comment]
This has been implemented from the first version. You can see it when the aircraft symbol turns red in the planner - that means that the turns required to reach that position would be too tight for the aircraft.

**Comment by Devirex** [comment]
Ok, maybe i have never recognized it. i will check again.

**Comment by Devirex** [comment]
hi, ok now i tried four times on different airports with the smallest possible turn radius and had no issues. The issue i had was that tug and plane were not able to drive the smallest choosable corner to 90 deg. But i think i had some issue on my side, like thrust levler not in idle while starting or feet on one of my toe brakes. 
You can close the issue.

**Comment by skiselkov** [comment]
Ok, thanks for the update.
