### ISSUE TITLE
Celebi Livery AST-3F

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#122]
[Celebi.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1250514/Celebi.livery.zip)
Celebi is operating in Vienna, Budapest, Mumbai, Delhi, Ahmedabad and in many airports in Turkey.

**Comment by fregate083** [comment]
Hi,

Thanks a lot for all these improvments.
Only a question :
How would things are going when several liveries together ?
For example in Vienna, already the Vienna liveries, in France (at LFMN for example, Avia partner and Air France liveries)

Would it be also possible to chose our livery ?

Thanks a lot

Regards

Alexandre

**Comment by liebbe10** [comment]
As far as I'm concerned if multiple liveries exist they are chosen randomly each time you use the pushback plugin

**Comment by skiselkov** [comment]
@fregate083 For details on the livery selection logic see https://github.com/skiselkov/BetterPushbackC/blob/master/objects/tugs/LIVERIES_HOWTO.txt

**Comment by skiselkov** [comment]
@liebbe10 Can you please provide a detailed airport list for this livery? I don't like using very wide matching rules.

**Comment by liebbe10** [comment]
For Austria, Hungary and India it is easy...the only information for Turkey was that they operate in more than 30 airports

**Comment by skiselkov** [comment]
Closing as implemented.
