### ISSUE TITLE
SAS Livery AST-3F

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#126]
I made the SAS Ground Handling livery for Denmark, Sweden and Norway.
[SAS.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1254023/SAS.livery.zip)

**Comment by skiselkov** [comment]
Thanks, added, but again, can you please find a tighter list of airports where SAS provides ground services?

**Comment by liebbe10** [comment]
Wikipedia says they are located in 30 airports in Denmark, Sweden and Norway...on their website i only find Stockholm / Arlanda , Gothenburg / Landvetter and Malmö / Sturup

**Comment by skiselkov** [comment]
Closing as implemented.

**Comment by JoseBDA** [comment]
Hi,

I wonder if you need some more Portuguese audio; I’m thinking of warning for taxi/landing lights ON. In case you need some more, just tell me what I need to do.

Best regards,

José B. Almeida
Universidade do Minho
Physics Department
josebda@gmail.com
