### ISSUE TITLE
Download Mirror

### ISSUE THREAD

**Issue by srykho22** [skiselkov/BetterPushbackC#129]
Hello

Could you please place a download mirror? The release download is slow, then it stops. Even the master download is faster, but I realized that it doesn't contain the plugin.

Thanks in advance

**Comment by skiselkov** [comment]
Can you please specify what "master" download is faster? Presently the plugin is hosted on Github's servers, so if they are a little slow, then that's not something I can affect (and I won't mirror it on x-plane.org, because the plugin is not yet finished, it is still considered beta software and might break at times).

**Comment by srykho22** [comment]
The master download I used was the one that shows up when you click the "code" link. I find it strange that it actually downloaded due to it's larger size. I've already attempted to download it on different devices, and use VPN. If it's not possible, could you please send me the file via other means, such as Google Drive?

**Comment by srykho22** [comment]
I utilized the "download as ZIP" option

**Comment by skiselkov** [comment]
I think you maybe have been download the source code archives. You don't want those. You want the one labeled `BetterPushback.zip`:
![shot](https://user-images.githubusercontent.com/3300688/29897877-4d0ada64-8de3-11e7-973d-07534ca5c11f.png)
Here's the exact link to the correct file: https://github.com/skiselkov/BetterPushbackC/releases/download/v0.44/BetterPushback.zip

**Comment by srykho22** [comment]
The link on the source code archives is the slow download. I downloaded the master file out of desperation, and it actually downloaded. The download of the actual plugin goes at about 5kbps, then it stops at 5MB. Could you please send me the file via Google Drive? It will actually download on my computer that way. Maybe it would be better if there was a public drive folder as the mirror download :)

**Comment by srykho22** [comment]
Sorry, I meant the download of the plugin was slow, the one on the source code archive actually downloaded

**Comment by srykho22** [comment]
I think there was a misunderstanding, but I'm saying that it doesn't wrk when I attempt to download the plugin, and the one on the source code archives actually downloades

**Comment by skiselkov** [comment]
I'm sorry, I don't have a Google Drive. Something must be wrong with your Internet connection or you are running some sort of content filter. The download works fine for everybody else, so the problem likely exists on your end. Please try and have a friend download it for you, or try from another location.
