### ISSUE TITLE
Zibo B738, dont turn in push

### ISSUE THREAD

**Issue by Curpling** [skiselkov/BetterPushbackC#13]
Got the latest Zibo B738X, when planning a turn in the push, the push truck just goes straight. Tested with stock B738 and then everything works as it should, but not with ZIBO's B738X

**Comment by skiselkov** [comment]
This has been reported before. It's a problem in Zibo's 737 mod and a patch has been submitted to Zibo's mod forum link: http://forums.x-plane.org/index.php?/forums/topic/111305-boeing-b738-800-modified/&do=findComment&comment=1211370
