### ISSUE TITLE
info.cfg for msgs

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#131]
Maybe it would be a good idea to implement a info.cfg file format for speech messages...Then it would be possible to upload your own messages to for example the x-plane forum when the plugin is released

**Comment by skiselkov** [comment]
I'm implementing a feature where if multiple sound sets match, then one is selected at random. Therefore, there will be no requirement for an `info.cfg` to configure the sound sets - the mere presence of the sound set is already all that is needed.

**Comment by liebbe10** [comment]
But how would I specify where the sound files should be played? I'm talking about the possibility that when the plugin will be released, some people might want to add their own language packs without requiring the implementation of you the developer.

**Comment by skiselkov** [comment]
That is determined by the folder name in which the sound set is present. The formats in use currently are:
1. ISO 639-1 code, followed by underscore character, followed by ISO-3166-1 alpha 2 code. Example: "pt_BR". Denotes a language pack for a specific language dialect spoken in a particular country.
2. ISO 639-1 only. Example: "ru". Denotes a language pack used as a generic language fallback if a country-specific pack isn't available.
3. "en", followed by an underscore character, followed by ISO-3166-1 alpha 2 code. Example: "en_BR". This denotes a localized accented English pack specific to one country.
4. "en", followed by a dash character, followed by ISO-639-1 code. Example: "en-pt". Denotes a localized accented English pack used as a fallback when the local country language differs from English, but a local country pack following rule 3 isn't available.

This is how all language packs are put together in BP. There is no hard-coded list of language packs in BP, everything is read dynamically at runtime. I will put the above explanation into a README into the `msgs` directory in case other people are also unclear about this.

**Comment by liebbe10** [comment]
ah sorry I thought it was hard coded into the plugin...the more I now about the plugin, the more I'm impressed about your work!!!
