### ISSUE TITLE
Lines on the ground around tug

### ISSUE THREAD

**Issue by ShaneD-VPA** [skiselkov/BetterPushbackC#136]
There are lines around the AST_1X tug as if the tug is floating on a plate, I have highlighted the lines in red
![lines](https://user-images.githubusercontent.com/31504973/29994294-3f124c3e-8fc4-11e7-93b9-87ba416c516d.jpg)

**Comment by skiselkov** [comment]
That's the baked ambient occlusion quad doing bogus shadow casting. Shadow casting should be disabled on that object, but perhaps I missed something, will check & fix as necessary.

**Comment by skiselkov** [comment]
Can you please try the following file. This is a new tug object. Use it to replace the one in the plugin under `objects/tugs/AST-1X/AST-1X.obj`.
[AST-1X.obj.zip](https://github.com/skiselkov/BetterPushbackC/files/1272098/AST-1X.obj.zip)

**Comment by ShaneD-VPA** [comment]
Thank you, I can confirm the shadow has disappeared with the new tug object installed

![no shadows](https://user-images.githubusercontent.com/31504973/29999038-e8268a02-9031-11e7-9da4-975125985f51.jpg)

**Comment by skiselkov** [comment]
Thanks for testing, closing as resolved.

**Comment by ShaneD-VPA** [comment]
glad to help
