### ISSUE TITLE
Gap between Electric tug and aircraft

### ISSUE THREAD

**Issue by ShaneD-VPA** [skiselkov/BetterPushbackC#137]
I have been using the Super King Air B-200 from Matt Fuller as my goto twin, now painted in the colours of the VA I fly for, but after calling the tug the connection sequence happens but the link (strap) doesn't reach the gear strut, is this a 3rd party aircraft thing or should BP detect the strut automatically ?
![gap](https://user-images.githubusercontent.com/31504973/29994335-620972ca-8fc5-11e7-8649-b79d566b343f.jpg)

**Comment by skiselkov** [comment]
This is a bug in the aircraft, not BetterPushback. BP reads the nose gear location from the tire_z_nodeflection dataref, which is where X-Plane thinks the longitudinal centerpoints of the tires are (this is defined in Plane Maker). The model author also has the option of supplying a custom visual model. If that doesn't properly align with the physics model, then what you are seeing above is the result. So this is something the aircraft author must fix, as BP has no other way of determining component locations (the 3D model is just that - a pretty picture and nothing more).

**Comment by ShaneD-VPA** [comment]
Understood, thanks

 

ShaneD
