### ISSUE TITLE
Crash when X-Plane 10 closes

### ISSUE THREAD

**Issue by McDonne11** [skiselkov/BetterPushbackC#14]
Hello!
When I trying to close X-Plane, appears the error:
"Microsoft Visual C ++ Runtime Library This application has been requested the Runtime to terminate it in an unusual way. Please, contact the application support team for more information". And crashing X-Plane.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1151723/Log.txt)
Thanx in advance!

**Comment by McDonne11** [comment]
Also, after performing pushback (MD-80 by RotateSim), after disconecting tug X-Plane has crashed with error StackHash_6131.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1151922/Log.txt)

**Comment by skiselkov** [comment]
Thank you for the report, I believe I understand what the problem is. Fix is in the works.

**Comment by skiselkov** [comment]
Please test with release v0.13.

**Comment by McDonne11** [comment]
Many Thanx!
I'll test it right now.

**Comment by McDonne11** [comment]
Thank you so much! Both problems are gone.

**Comment by skiselkov** [comment]
Thanks for reporting & testing.
