### ISSUE TITLE
727 FlyJsim

### ISSUE THREAD

**Issue by helmuthmoya** [skiselkov/BetterPushbackC#140]
Hi sir, i was wondering if is posible to fix the pushback to 727 FlyJsim?

Thank you.

**Comment by skiselkov** [comment]
I'm not aware of any problem with the FJS 727. I don't own it, but I've seen it work flawlessly on Twitch streams. Can you please provide a more detailed description of the problem?

**Comment by helmuthmoya** [comment]
Hi thank you for help me and answer me,  the problem what appears is this:

(Pushback failure: aircraft appears to have miltiple steerable gears)
![betterpushback727](https://user-images.githubusercontent.com/31635095/30606682-20b926c8-9d38-11e7-9598-a7f9931df565.jpg)

Thank you.

**Comment by skiselkov** [comment]
Can you please attach your `Log.txt`?

**Comment by helmuthmoya** [comment]
ok, im sorry i will sent you.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1315843/Log.txt)

Thank you.

**Comment by skiselkov** [comment]
You are running an outdated version. Newer versions have had this problem fixed. Please *always* test the latest version before filing bugs.
