### ISSUE TITLE
Driving Zigzag

### ISSUE THREAD

**Issue by jerox01** [skiselkov/BetterPushbackC#141]
Hi Skiselkov,

Please take a look at this video I just made: https://www.youtube.com/watch?v=lyydtSZobQ8

I tried the plugin with different airports and ramps, but this problem occurs every time as soon as the cart needs to make its last turn to the taxiway.

I'm using X-Plane 11 on a Mac.

I really hope you can help me. It looks like a great plugin!

Thx!

**Comment by jerox01** [comment]
@skiselkov 
Looks like this problems only happens with the Zibo 737-800 mod!
I tried it with the stock 737 without any problems.

I hope there is a solution so I can use the Zibo mod and BetterPushback together.

Please let me know something.

**Comment by mmerelles** [comment]
This happened to me as well, problem seems to rise when the termac is wet only, i.e. raining!

**Comment by CDN791M** [comment]
Is also occurring on Flight Factor 757-200 (Win10, XP11.05).  Is this related to Austin's tire modeling changes?

**Comment by skiselkov** [comment]
Might be a wet taxiway traction problem. Will investigate.

**Comment by CDN791M** [comment]
It's happening on dry taxiways.  I was under ISA conditions when it occured.

**Comment by skiselkov** [comment]
Got any updates here? Can you test BP 0.46?

**Comment by CDN791M** [comment]
Hi;
  BP v0.46 is working again with the FF 757 extended v2.1.11!  Well done!
  this is in XP11.10b8.
  cheers,
  ed
  
  
   ---------- Original Message ----------
   From: Saso Kiselkov <notifications@github.com>
   Date: November 18, 2017 at 8:14 AM
   
   
   Got any updates here? Can you test BP 0.46?

**Comment by skiselkov** [comment]
Thanks for the update. closing as fixed.
