### ISSUE TITLE
FlyJSim Boeing 727 Series issue

### ISSUE THREAD

**Issue by McDonne11** [skiselkov/BetterPushbackC#15]
![default](https://user-images.githubusercontent.com/30194437/28282263-7207a60c-6b5c-11e7-9607-0c394e19d344.JPG)

**Comment by skiselkov** [comment]
Unfortunately I don't have the 727. However, you can help me debug this. Please refer to the procedure for obtaining DataRefTool in https://github.com/skiselkov/BetterPushbackC/issues/4 . Once you have it, please find and put a comment here the values of the following datarefs:

* `sim/aircraft/overflow/acf_gear_steers`
* `sim/aircraft/parts/acf_gear_type`

This will help me figure out how to work around the problem.

**Comment by McDonne11** [comment]
Ok. Will now be.

**Comment by McDonne11** [comment]
![1](https://user-images.githubusercontent.com/30194437/28283314-fc5a9e1a-6b5f-11e7-8c18-c9a7f1c79aa6.JPG)
![2](https://user-images.githubusercontent.com/30194437/28283315-fc82bcba-6b5f-11e7-81a0-fd6ae5db1054.JPG)

**Comment by skiselkov** [comment]
Thanks for the data. I'll try to find a solution.

**Comment by skiselkov** [comment]
Fixed in v0.16. Please test and confirm.

**Comment by McDonne11** [comment]
Thanx a lot!
As you can see, now everything works fine!:)
![727-200adv_1](https://user-images.githubusercontent.com/30194437/28302100-f5d3e476-6bbd-11e7-8301-d54ddf185619.png)
![727-200adv_2](https://user-images.githubusercontent.com/30194437/28302099-f5d3e48a-6bbd-11e7-9b82-29dea4074c66.png)
![727-200adv_3](https://user-images.githubusercontent.com/30194437/28302101-f5d6cefc-6bbd-11e7-8f63-13af908e7286.png)

**Comment by skiselkov** [comment]
Thanks for the confirmation.
