### ISSUE TITLE
Pause during pushback

### ISSUE THREAD

**Issue by giahuy45** [skiselkov/BetterPushbackC#151]
Hello 

I quite enjoy your add-on. This is one of the better push back out there that i have ever seen in x-plane. I want to request a new feature for this add-on. During push back or tow the aircraft, you should have an option in order to pause the push back. Reason being that some aircraft has higher priority than you and they can push out first before you can push or they need to hold short of taxiway before  continue towing

Anyway, keep up the good work.

**Comment by skiselkov** [comment]
Have you tried simply setting the parking brake? Does that not work for some reason? BP reacts to brake settings and if you apply brakes, it should stop pushing and wait for you to release them.

**Comment by giahuy45** [comment]
If the tow already moving, if you release the brake or not, it's still going to be on the platform and it's still going to move forward unless you talk to the driver to hold short. Using the parking brake is unrealistic

**Comment by giahuy45** [comment]
Bump, This should be added feature in the next update.

**Comment by skiselkov** [comment]
I don't want to be creating new commands just for this eventuality - almost nobody is going to bind a custom command to pause the pushback "just in case". Hence why I reused the parking brake command. Consider a user convenience thing. Of course in reality you'd have to talk to the driver. But in reality you wouldn't be clicking menus to call for push or hover 300 ft in the air to plan a pushback either. I consider the parking brake workaround as a reasonable limitation of the practicality of a simulation.
