### ISSUE TITLE
Dollypad for Helicopter

### ISSUE THREAD

**Issue by Milki52** [skiselkov/BetterPushbackC#152]
Is it possible to include a funktion to pull a dolly? It will be awesome when it will be possible. 

http://www.aircrafttowbar.eu/communities/4/004/007/175/944//images/4532102539_348x262.jpg

Or something like a "helicarrier"
http://www.paravion.com/wp-content/uploads/2012/03/IMG_1592.jpg

Thanks for your great plugin

**Comment by skiselkov** [comment]
I'm sorry, but this seems like a feature that get rarely (if ever) used, so I won't be implementing this for now.
