### ISSUE TITLE
Tow my plane in a hangar

### ISSUE THREAD

**Issue by XPFlyer** [skiselkov/BetterPushbackC#156]
Is there a way to tow my plane inside a hangar ? I was looking for a manual towing with joystick to do this but did not find this option. 

What is the best way of doing that.

BTW, congratulations for a beautiful add-on.

**Comment by Rodeo314** [comment]
Well you can plan the pushback (but also "pullforward") in any direction, just make a route taking your aircraft from its present position to the hangar…

**Comment by skiselkov** [comment]
There is currently no way for manual towing of the aircraft. You need to pre-plan a route and then let BP operate automatically. It's supposed to simulate you sitting in the aircraft and being driven around by a tow truck driver. BP is not intended to be a tow truck driving simulation.
