### ISSUE TITLE
Plugin not compatible with latest ZIBO version

### ISSUE THREAD

**Issue by Gregc320** [skiselkov/BetterPushbackC#159]
Hi just to let you know - says it in the title the better pushback plugin doesn't seem to be compatible with the latest ZIBO mod version, works fine with every other aircraft it seems.

Thanks

**Comment by birdydma** [comment]
No problem here.

Hard to help without any details.

**Comment by skiselkov** [comment]
Closing as incomplete & likely dup of #155.
