### ISSUE TITLE
Smartcopilot integration

### ISSUE THREAD

**Issue by skiselkov** [skiselkov/BetterPushbackC#16]
Users have requested smartcopilot integration for shared cockpit usage. This will be implemented by adding the following datarefs & behaviors:
* Master/slave must not be switched during pushback (undefined behavior may result). It's possible to observe if BetterPushback is running by monitoring the read-only boolean dataref `bp/started` (this dataref should NOT be synced, it's only a hint to smartcopilot whether switching is safe).
* `bp/slave_mode=0|1`: This needs to be set to `1` on the slave machine.
* `bp/op_complete=0|1`: Signal from master to slave that the pushback operation is complete. This needs to be synced from master to slave.
* `bp/tug_name[string]`: This will be a string identifying which tug model BP selected. This needs to be synced from master to slave.
* the command `BetterPushback/start` should be synced. There's no need to sync any other commands. The planning GUI is disabled on the slave machine and stopping of the pushback can only be performed by the master machine.

**Comment by skiselkov** [comment]
Implemented in v0.14. Please test.

**Comment by birdydma** [comment]
It works as intended. There is a remaining problem. The slave must have DRT or DRE installed to switch bp/slave_mode to 1. 
A test with scp/api/ismaster (0 = no connection, 1 = slave, 2 = master) could do the job.

**Comment by skiselkov** [comment]
Can you not set `bp/slave_mode` automatically via smartcopilot?

**Comment by birdydma** [comment]
Nothing to do.
If we add  bp/slave_mode in any section, the value (0 or 1) will be shared 

Non similar values are override/override, switching from 0 to 1 for a pilot and from 1 to 0 for the other one when commands are released.

For example you will find in this section:

sim/operation/override/override_joystick_heading, sim/operation/override/override_wheel_steer, etc..

**Comment by skiselkov** [comment]
Ok, so if I understand you right, you can't force smartcopilot to set bp/slave_mode=1 on the slave machine *only*, am I correct?

**Comment by birdydma** [comment]
Exact,

So, if there is no scp/api/ismaster: there is no smartco plugin. bp/slave mode=0

If scp/api/ismaster is found and =0 , there is no connection. bp/slave_mode=0

If scp/api/ismaster = 1, the connection is established, and this is the slave computer, bp/slave_mode will be =1

If scp/api/ismaster = 2, the connection is established, and this is the master computer, bp/slave_mode will be =0

Is it doable, as the plugin is loaded, but of course the connection is not yet established? Can the BP plugin monitor the status of scp/api/ismaster (when present) to write the correct value in bp/slave_mode?

**Comment by skiselkov** [comment]
Thanks for the clarification, I understand now. No problem, I'll put the smartcopilot detection directly into BP.

**Comment by skiselkov** [comment]
Implemented smartcopilot connection detection in v0.17. Please test.

**Comment by birdydma** [comment]
Sorry, no joy. bp/slave_mode of the slave stays at 0.

Very, very minor, the slave does not hear the plan_end.wav.

**Comment by skiselkov** [comment]
Ok thanks, I guess I'll have to test it directly in smartcopilot myself.

**Comment by birdydma** [comment]
Ok, let me know. As i have 2 computers on a LAN, it is easy for me. I don't have to wait for an available copilot.

**Comment by skiselkov** [comment]
I believe I've got this resolved. Smartcopilot was initializing its datarefs later than BetterPushback was looking for them. In the next release (will be released shortly) will fix this.

**Comment by skiselkov** [comment]
Should be fixed in v0.18.

**Comment by birdydma** [comment]
0.19 tested: Target reached. You make my day.

Now, the new feature (connect first) is not sync. May i ask a nice custom command: BetterPushback/connect_first?

0.19 also tested with the stock 747. Pb use the right tug for this plane. But i have no file to do the test with smartco. Should work, but if you have any doubt, ask me. I will write a simple file for the test.

**Comment by skiselkov** [comment]
> Now, the new feature (connect first) is not sync. May i ask a nice custom command: BetterPushback/connect_first?

Sorry about that. I'll prepare a custom command that you can sync.

**Comment by skiselkov** [comment]
Please test version 0.20. I added a new command & dataref that need to be synced:
* `BetterPushback/connect_first` - command that needs to be synced from master to slave. This tells BP to start the pushback without a plan and pause before attempting to actually start the push operation (i.e. the pushback progresses only up to the "connected" stage).
* `bp/plan_complete` - boolean dataref that needs to be synced from master to slave (informs BP when the planning phase is complete if the user requested to "connect first").

**Comment by birdydma** [comment]
Test done.

Perfect.

**Comment by skiselkov** [comment]
Thank you. I'll close this issue for now. If you run into any trouble, feel free to open a new one.
