### ISSUE TITLE
Betterpushback does not work with the xplane 11.10b5

### ISSUE THREAD

**Issue by jefken153** [skiselkov/BetterPushbackC#164]
Hi,
I insstalled Betterpuschback with xplane11.05.r2 the original installation from xplane11 I which I bought, I had no problems.
After an automatic update from Xplane11 to 11.10b5 went wrong and betterpushback did not work anymore. Going back to 11<.05r2 no more problems.
what is the cause?

**Comment by skiselkov** [comment]
Please test BP 0.45, as that has XP11.10-specific compatibility changes.

**Comment by jefken153** [comment]
Sorry but I use still BP 0.45

**Comment by skiselkov** [comment]
"still"? Also, please be a bit more specific than simply "did not work anymore". I need a Log.txt file, screenshots and best would also be a video of it "not working".

**Comment by jefken153** [comment]
I have downloaded BP 0.45 today and  I on-updated the 11 10b5 to 11 05r2 and it works
then 10 minutes ago I updated to 11 10b5 and BP045 does not work
here my 
[Log.zip](https://github.com/skiselkov/BetterPushbackC/files/1431573/Log.zip)
a video
[bandicam 2017-10-31 17-59-37-922.zip](https://github.com/skiselkov/BetterPushbackC/files/1431608/bandicam.2017-10-31.17-59-37-922.zip)

thanks for the help

**Comment by birdydma** [comment]
In your log.txt, i can read:
2017-10-31 17:44:53 BetterPushback[xplane.c:424]: This is BetterPushback-v0.44 libacfutils-cc3c447

You have not installed the 0.45 release. This the same line in my log.txt:
2017-10-31 16:44:56 BetterPushback[xplane.c:538]: This is BetterPushback-v0.45 libacfutils-405a90e

**Comment by jefken153** [comment]
Thank you its working now in 11 10b5

**Comment by jefken153** [comment]
BP works fine with the big airplanes like 737 with c172 it's more difficult.

**Comment by skiselkov** [comment]
Closing this now, as the performance on small airplanes isn't related to it not functioning at all. Glad you got the 0.44/0.45 issue resolved, @birdydma appreciate your help on this.
@jefken153 If you can please detail what problems you are having with BP on small aircraft, please file another issue about that and provide the details of the broken behavior in there. Thanks for the report!
