### ISSUE TITLE
No voice audio in v0.45

### ISSUE THREAD

**Issue by sizziano** [skiselkov/BetterPushbackC#165]
Unable to hear voices regardless of what audio source is picked.

Edit: Here is my log.txt in case it contains useful info. Other than no voice sounds the plugin seems to work as intended.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1435414/Log.txt)

**Comment by sizziano** [comment]
Fixed by deleting the X-Plane.prf file in the Preferences folder.

**Comment by skiselkov** [comment]
Thanks for letting me know that solves it. Closing this now.
