### ISSUE TITLE
Pushback stickiness on Saab 340 on XP10

### ISSUE THREAD

**Issue by meistersoda** [skiselkov/BetterPushbackC#17]
Hi,

first of all: thank you for a great plugin. I love the path feature, so I can stay in cockpit. Do you plan to integrate a smaller tug for smaller aircraft? I am flying CRJ200 and Challenger 300 quite often and they need to get out of their parking positions, too. :) But no hurry, I am glad the plugin is working for Zibo right now!

Thanks,
Tim

**Comment by skiselkov** [comment]
The primary target for the plugin right now are narrow body jets. in the 50-150t class, hence the choice of tug to model first. My next target is wide body jets up to the A380 and I've already started work on the AST-1X 680 model. After that I will turn my focus to something for small aircraft, maybe something like a LEKTRO.

**Comment by birdydma** [comment]
Will a Lektro push an AN 24 or a SAAB?

May be, there is a room between Lektro and our tug for narrow body jets.

http://www.aeroexpo.online/aeronautic-manufacturer/aircraft-tractor-874.html

A question. To chose a tow, do you test the MTOW stored in sim/aircraft/weight/acf_m_max?

**Comment by skiselkov** [comment]
> Will a Lektro push an AN 24 or a SAAB?

The An-24 is unfortunately not compatible. There's some issue with releasing the parking brake after pushback and seeing as it's X-Plane 10-only and unlikely to be supported in the future, I'm not holding my hopes up. The SAAB 340A should be handled by the AST-3F currently in the plugin, but the Lektro will handle it easily as well. Lektro actually has a number of models. Currently I'm looking at the AP88 series as a good candidate (up to 54t MTOW and can handle things even down to single-engine trainers): http://www.lektro.com/series/ap88-series/

> A question. To chose a tow, do you test the MTOW stored in sim/aircraft/weight/acf_m_max?

The tug selection methodology is quite a bit more complicated. For each tug, we have the following set of parameters:

1. minimum and maximum MTOW
1. minimum and maximum wheel size
1. an optional gear type compatibility mask (the Goldhofers for example can only handle a two-wheels-side-by-side nose gear)

All of these are compared to the actual aircraft in determining which tug best suits the aircraft. If multiple tugs fit the selection criteria, the selected tug is randomized so there is some variety.

**Comment by birdydma** [comment]
Understood.

Thank you for your time.

**Comment by skiselkov** [comment]
Making good progress on this, should have something test-ready in a few days.
![ap88](https://user-images.githubusercontent.com/3300688/28487535-d64101c0-6e92-11e7-934d-10d371a94733.png)

**Comment by birdydma** [comment]
Well done Saso,

0.23 tested with the Saab and smartco.

-I don't know the speed of such a tug pushing a Saab 340, but it seems very slow, too slow even if it is real, and the push is straight on only (does not follow the curve of my plan). But this is only my first attempt.

-Nobody on the seats.

**Comment by skiselkov** [comment]
No, that looks like a bug. I'm analyzing.

**Comment by skiselkov** [comment]
You can actually work around it now by just lightly depressing the brakes and letting go.

**Comment by birdydma** [comment]
A little acceleration during about 1 sec playing with toe brakes.

Only the first straight segment is done.

PS: with the Saab, i run Win 10.

**Comment by skiselkov** [comment]
Ok, I've got the source located. You're running in XP10, right? Seeing as the Saab 340 isn't officially supported in XP11, I assume the answer is yes. XP10's tire model is very "sticky" at slow speeds. Below about 0.5 m/s the aircraft has the tendency to just get "stuck" to the ground if the plugin reduces the pushing force below about 10kN (this scales with aircraft mass of course). This is normally handled in BP by having a "breakaway threshold speed" below which BP will not reduce push force to control acceleration. This threshold is higher for XP10 to account for this ground stickiness, but due to a bug in sim version detection, it was not getting increased. I'll have a build with the fix available shortly.

**Comment by birdydma** [comment]
Always running XP 10, same gate and planning, but with the stock B58. No problem here.

Don't spend too much time with XP 10. At some point, we will have a 1.5 release (XP 11 specific). for the Saab. Also hope for a TU154M XP 11 compatible.

**Comment by birdydma** [comment]
Tests of this day were done with the 0.23 release.

**Comment by skiselkov** [comment]
Please test on release 0.24, should fix the stickiness.

**Comment by birdydma** [comment]
Good day,

release 0.25: BP choose the AST-1X.tug for the Saab.

This morning, the tug is silly. It sits near the plane, the value of custom datarefs for cab position, driver orientation, wheels, winch, are playing yoyo.

Later,to catch the Lektro, i will reboot X Plane, several times if necessary, and see what happen with this one.

**Comment by birdydma** [comment]
No joy. I can't catch the Lektro.

**Comment by birdydma** [comment]
New test: XP 11 and  the Ixeg: "Tow is coming up", and nothing happen.

**Comment by skiselkov** [comment]
Hang on, I made a release mistake. Emergency release incoming.

**Comment by skiselkov** [comment]
Should be fixed now. Sorry for the confusion.

**Comment by birdydma** [comment]
Wow, don't be sorry,

Back to the 0.24 release with the Saab.

Test 1. Engines not running. Only a straight segment is done.
Test 2: Engines running, NWS activated. Only a straight segment is done.
Test 3:  Engines running, NWS activated. I drive the tug with my pedals. It turns despite small flicker of the tug, but after the turn, it's again very slow.

**Comment by birdydma** [comment]
Some more about the Saab.
Engine running, NWS engaged, the plane don't move. sim/operation/override/override_wheel_steer is set to 1 by the plugin of the plane, i can't turn the nose wheel.
Now, as soon as the plane is moving (forward with engines, or backward with the tug), the override is switched to 0, and i can turn the nose wheel with the pedals.

At some point, probably when the tug should turn for the second leg of my plan, the tug is very slow, and the override is continuously switching between 0 and 1, this is why the turn is not done.

**Comment by skiselkov** [comment]
I need to do some more analysis on this, because on my install it was working fine last I checked.

**Comment by birdydma** [comment]
This was with the 0.24 release. Do you need a test with the 0.27?

**Comment by birdydma** [comment]
A little more (release 0.28). This is for the Saab only, as i have no problem with the stock Baron and 747 of XP 10.

sim/flightmodel/misc/nosewheel_speed is around 4 at the beginning of the push.

The value quickly slows down to 2, and below 1,  sim/operation/override/override_wheel_steer start switching between 1 and 0.

**Comment by birdydma** [comment]
Fixed with the new logic (0.42).

**Comment by skiselkov** [comment]
Wow, wasn't expecting that, but thanks for testing!
