### ISSUE TITLE
Tug goes crazy, can't find route

### ISSUE THREAD

**Issue by BluesmanEP** [skiselkov/BetterPushbackC#172]
I'm running XP 11.10b8 and version .46 of the pushback plugin.  When I start a pushback the tug seems to over-steer and then over-correct itself.  Often it won't be able to find it's position and will oscillate back and forth, never finishing the pushback procedure.  I've noticed this for at least version .45 and .46.

I find it with the FF A320, the FF 757-200.  I can test with other airliners if that's useful.  This also seems to happen at every airport.  I setup the pushback using the command attached to a keyboard shortcut - not using the iPad in the FF757.  I am also usually starting the engines during the push, but this doesn't seem to have any effect on the tug steering.

I've attached a small video of the issue, as well as the log.txt file.  Let me know if you need anything else.

Thanks for such a good plugin!

Here's the pushback route:
![screenshot_1](https://user-images.githubusercontent.com/1726991/32977144-3de7a1a2-cbf5-11e7-822c-669e8b771de8.png)

...the plugin info:
![screenshot_2](https://user-images.githubusercontent.com/1726991/32977191-5b59d90c-cbf6-11e7-8bd9-e6b530dfe3d9.png)

and the video in a zip file. (sorry for the low quality - I guess the XP default video settings aren't very good):
[757-200_xp11_1.zip](https://github.com/skiselkov/BetterPushbackC/files/1484367/757-200_xp11_1.zip)

**Comment by skiselkov** [comment]
This is a known issue and is a problem in the FF757v2. They've promised an update today that addresses this. Together with BP 0.46 this should take care of the incompatibilities.
