### ISSUE TITLE
FF Boeing 757 v2 - pushback is sliding transversely route

### ISSUE THREAD

**Issue by Igrok-kun** [skiselkov/BetterPushbackC#174]
Hello, @skiselkov !

I met a huge problem with your amazing plugin and good FF Boeing 757 v2. I use X-Plane 11 without any beta-versions (it supposed to be 11.05, I guess). I met the bug on BetterPushback ver. 0.44 and FF Boeing 757 v2.1.10 (the newest one). Then I downloaded BetterPushback ver. 0.46, but the bug is still there. The bug appeared nevertheless I use option "BetterPushbak" in planes settings or not. Also for me it comes undependently from option "Throttle block". I tried to use BetterPushback through sim menu and through FF built-in iPad.

Basically the problem in tug moving. When it starts go with a plane, for some reason, it turn to huge angles, going transversely pushback route. I should note, that it was okay with ver. 0.44 when my route was "pushback straight and then tow with left turn". But when it comes to "pushback with a turn" the tug goes mad.

Here are my screens to show how huge angles are. And tug moves among them with a full speed.
![757-rf_xp11_10](https://user-images.githubusercontent.com/30556727/32985839-7be28e88-ccd4-11e7-897a-c7c188885e94.png)
![757-rf_xp11_12](https://user-images.githubusercontent.com/30556727/32985840-7bfd7c48-ccd4-11e7-8206-ecf3372f88cf.png)

**Comment by Igrok-kun** [comment]
Sorry, my bet. I didn't know that FF published update for the aircraft (ver. 2.1.11 now). Problem solved there. You can delete the thread.

**Comment by skiselkov** [comment]
No worries, I worked with FF to get the 757v2 fixed and wanted to tell you that all you had to do was update, but you figured it out before I responded.
Have fun!
