### ISSUE TITLE
Mac XP11 Crash

### ISSUE THREAD

**Issue by SFHaines** [skiselkov/BetterPushbackC#18]
Greetings. I downloaded BetterPushback alpha v014 after seeing the promo video on YouTube. Must say this is a terrific plugin. By far the best push utility I have seen. Unfortunately every time I complete a push operation and dismiss the tractor the XP app crashes. The is XP11 running on a high-end iMac with loads of VRAM, etc. There seems to be no issue with the plugin itself. But after using it the application crashes. I have attached a recent log.txt file which may provide a clue. Hopefully there is an easy cure that doesn't require purchasing a PC :-)
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1154022/Log.txt)

**Comment by skiselkov** [comment]
Hey, no worries, my primary dev machine is a 3 year-old MBP, so your Mac is definitely good enough. The problem you describe seems familiar and I think it's something else. I suspect your problem is that you've installed an old version. Looking at the Log.txt you sent me:
```
Loaded: /Users/Steve/Desktop/X-PLANE 11/Resources/plugins/BetterPushback/64/mac.xpl (skiselkov.BetterPushback1.0).
```
It should say `skiselkov.BetterPushback.0.14`. Please try redownloading and reinstalling the latest release.

**Comment by brenoperucchi** [comment]
I'm too with the problem in the version 0.14 on Imac. 

```
Process:               X-Plane [11059]
Path:                  /Volumes/VOLUME/*/X-Plane.app/Contents/MacOS/X-Plane
Identifier:            com.laminar-research.X-Plane
Version:               11.02r2 (398)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           X-Plane [11059]
User ID:               501

Date/Time:             2017-07-17 18:23:25.959 -0300
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        72EFC5FD-E7A8-3AC4-0CAE-F6B3A5E5C154


Time Awake Since Boot: 1000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000fc0
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0xfc0:
--> 
    Kernel Alloc Once      000000000437f000-0000000004381000 [    8K] rw-/rwx SM=PRV  

Thread 0 Crashed:: MainThrd  Dispatch queue: com.apple.main-thread
0   libsystem_c.dylib             	0x00007fff92c89b52 strlen + 18
1   libsystem_c.dylib             	0x00007fff92ccf9fc __vfprintf + 5701
2   libsystem_c.dylib             	0x00007fff92cf8423 __v2printf + 699
3   libsystem_c.dylib             	0x00007fff92cdc92a _vsnprintf + 586
4   libsystem_c.dylib             	0x00007fff92cdc9d3 vsnprintf + 80
5   mac.xpl                       	0x000000007f493fc3 dr_create_f + 195
6   mac.xpl                       	0x000000007f48db70 tug_glob_init + 80
7   mac.xpl                       	0x000000007f491205 XPluginStart + 549
8   XPLM                          	0x000000007f10037c LoadOnePlugin(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) + 953
9   XPLM                          	0x000000007f0ff4e5 LoadFatPlugin(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 55
10  XPLM                          	0x000000007f0ffea5 XPLMFindAndLoadPlugins(char const*) + 1388
11  XPLM                          	0x000000007f0fee3e XPLMInitializePlugins + 158
12  com.laminar-research.X-Plane  	0x000000010443622b XPPInitializePlugins(char const*) + 4139
13  com.laminar-research.X-Plane  	0x0000000104d9f06c MACIBM_init(int, char const* const*) + 9916
14  com.laminar-research.X-Plane  	0x0000000104a42923 init_sim(int, char const* const*) + 67
15  com.laminar-research.X-Plane  	0x0000000104a42f12 main + 34
16  libdyld.dylib                 	0x00007fff92c53235 start + 1

```

**Comment by skiselkov** [comment]
@brenoperucchi This appears to be a different problem. I'll check it out immediately. I must have broken something in the mac build.

**Comment by skiselkov** [comment]
Problem located, new build coming momentarily.

**Comment by SFHaines** [comment]
Terrific. Incredibly fast response. Thanks!

**Comment by skiselkov** [comment]
Well this was a rather embarrassing bug. Fixed in v0.15.

**Comment by SFHaines** [comment]
Amazing! Will download and enjoy using this terrific plugin right away. Excellent work indeed. The best pusher utility I have seen.

**Comment by skiselkov** [comment]
@SFHaines Glad I could help. Don't forget to please let me know if the fix helped so I can close this issue.

**Comment by SFHaines** [comment]
Flawless! Worked perfectly. No crash. No issues. I will post a note on AVSIM also to let folks there know this issue has been solved. Thank you so much!

**Comment by skiselkov** [comment]
Thanks for the update.
