### ISSUE TITLE
Is BetterPushback XP10 compatible?

### ISSUE THREAD

**Issue by MarshallHilfman** [skiselkov/BetterPushbackC#188]
Hi, I saw this addon on a best XP11 addons video, but was wondering if it is compatible with XP10 as I don't have XP11.

**Comment by skiselkov** [comment]
Hello Marshall. Yes BP should work fine on XP10. Some of the driving algorithms might perform a little suboptimal due to XP10's terrible ground friction model, but other than that, it should work ok.

**Comment by MarshallHilfman** [comment]
Thank you.
