### ISSUE TITLE
Better Pushback is disabled

### ISSUE THREAD

**Issue by martinlest** [skiselkov/BetterPushbackC#195]
The last time I tried the plugin (XP11.11, latest version of Better Pushback 0.46) it was working fine. Now, although the folder is still there, it is marked as disabled. I can't re-enable it either via Plugin Admin. Read somewhere that the folder CIFP may be the cause, so I deleted it and copied over a backup one. Restarted XP11. Still Better Pushback won't work (it doesn't even appear in the plugin menu). What happened? I kind of rely on this now for my flights. How do I get it back please? Thanks

**Comment by skiselkov** [comment]
Can you please check your Log.txt (and also attach it to this issue) to see if it's not having trouble starting up. Being "disabled" in the plugin admin means Better Pushback couldn't initialize itself. This usually indicates an installation problem (e.g. missing some data files), but we'll know for sure if you post the Log.txt.

**Comment by martinlest** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1628491/Log.txt)
 Attached.

**Comment by skiselkov** [comment]
Seems like you are running X-Plane from a network drive and BetterPushback is having trouble writing into Output/caches to create its airport location cache. You might need to readjust your access permissions.

**Comment by martinlest** [comment]
I am not running X-Plane form a network drive - everything is on a local computer

**Comment by martinlest** [comment]
As I say, it was working fine till today and I haven't changed anything as far as I know

**Comment by martinlest** [comment]
Can't see any reason for that supposedly network startup. I rebooted the PC and the log.txt shows the proper path - and now Better Pushback is working again. Thanks for the help; if I get this again I'll know what to look for, even if I don't know why it's happening.

**Comment by skiselkov** [comment]
Thanks for the update.

**Comment by Dibado** [comment]
I have tried everything I know to enable Better Pushback.  Everything in my plug-in folder is enabled and works except for this fine program.  I hope something can be done.

**Comment by Hutchinson5033** [comment]
I too am having problems getting Better Pushback to work. It does not appear to be recognised by X-plane and does not show up in the list of plug-ins.
I am using X-Plane 11.35 on a Windows 10 Pro PC.
Any guidance would be much appreciated.
I attach my log file if that may help.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3602953/Log.txt)

**Comment by Alan377** [comment]
Install or transfer the X-Plane to the root of the disk.
The folder name should only be X-Plane, other names are excluded.
Everything will work.
Also had a problem with better push back and xlg 3.32 (denied access to create a cache+Plugin Admin disable ), renamed the folder from X-Plane 11 to X-Plane, it worked.

**Comment by Tw1993** [comment]
I just reinstalled X-Plane on my new computer and I can't get BetterPushback to enable. Have reinstalled several times but no luck. My main X-Plane folders is in the My Documents folder on my computer. Any help?
