### ISSUE TITLE
Stop pushback

### ISSUE THREAD

**Issue by Rodeo314** [skiselkov/BetterPushbackC#198]
While BetterPushback works fine most of the time, sometimes it overshoots the requested target position (e.g. with a snowy ground surface, I find). I'e also had an issue where it runs around in circles (A320 build 189x, BP 0.46).

These problems wouldn't be showstoppers if one could stop the pushback partway through, but the stop pushback menu item never worked for me, FWIW (it doesn't even acknowledge my request to stop in any way, no messages in the log either). As far as I can tell it might as well be a no-op.

I've had success stopping a runaway tug using the parking brake instead (tug stops), but again, the "stop pushback" menu item does nothing, and there seems to be no other way to terminate or otherwise disconnect the tug (and while the tug doesn't move while the brake it set, most aircraft are otherwise unusable until the tug releases the nose wheel).

The ideal situation is of course to try and fix those corner cases so that pushback performs as expected, but it would be really nice if the stop feature could get some real love, because having to reload the aircraft each time BetterPushback gets into a bad state is a terrible PITA.

**Comment by Rodeo314** [comment]
I wish I had more time to look into this and the other issue I'm having, but as far as I can tell:

- bp_stop() sets last_hdg to NAN
- bp_stop() deletes all remaining segments
- bp_stop() does NOT attempt to update/set the step, to e.g. PB_STEP_STOPPING

… so betterpushback (keeping in mind my very limited understanding of the code) will probably always attempt to finish the already-in-progress segment?

There may be reasons why force-setting the step PB_STEP_STOPPING is a bad idea, but there could be checkable conditions (e.g. aircraft is stationary and parking brake is set) where force-setting the step is safe (and should be done), or there could be another step, BP_STEP_FORCE_STOPPING which could more forcibly stop BP while making sure to reset/sanitize the state to a point where we can then skip directly to the stopping step.

Otherwise it seems like bp_stop() is essentially useless when the "problem" segment is already in progress (wouldn't that almost always be the case, too)?

Else perhaps it would be easier to create another function that immediately stops the tug and instantly resets everything (and add an "emergency stop" menu item)?

**Comment by nubbix** [comment]
I have the same problem, pushback vehicle moves the plane in full 360 circles, also the option to stop pushback in the menu, do not work. Looks like it falls into a infinitive loop

**Comment by ChadScott** [comment]
I just saw this problem yesterday and I think I have steps to reproduce it... stock scenery, KOAK, gate 7. Set up a pushback with the tail headed to port onto the apron centerline. For some reason Betterpushback either refuses to do the push or, if you can finagle it to start (I stop, reconnect, and start) it'll happily push you straight across the entire airport. After using the parking break to stop, it won't disconnect and just pushes you around in circles.
