### ISSUE TITLE
Plugin doesn't work in Windows 7 x64 + X-Plane 10.51r2.

### ISSUE THREAD

**Issue by McDonne11** [skiselkov/BetterPushbackC#2]
Pre-Planing works well. When call the tug, appears the error:
"Microsoft Visual C ++ Runtime Library This application has been requested the Runtime to terminate it in an unusual way. Please, contact the application support team for more information". And crashing X-Plane.

**Comment by skiselkov** [comment]
Can you please attach the Log.txt that was generated with this? The information in the file is very important to debugging this.

**Comment by McDonne11** [comment]
Thank you for your responsiveness and so prompt reply!
Log file is attached.
One of the best plugins! If not the best.
Thank you in advance for your help.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1150569/Log.txt)

**Comment by hey-eng** [comment]
Same issue in Windows 10 Pro x64 + XP 10.51r2, regardless of the plane used.

**Comment by McDonne11** [comment]
Most likely, the problem is in the X-Plane version, not in the OS version.

**Comment by skiselkov** [comment]
Thanks for the log. I have a fix in and will be publishing it shortly.

**Comment by skiselkov** [comment]
Fixed in v0.11.
