### ISSUE TITLE
Old position in Pre-Planing saves in new flight [X-Plane 10]

### ISSUE THREAD

**Issue by McDonne11** [skiselkov/BetterPushbackC#20]
Before assigning a new position, need to press a "Delete" key and only then add a new one.
Thank you in advance.

**Comment by skiselkov** [comment]
What you are describing isn't a bug, it's a feature. Routes are deliberately persisted across flights to allow for reuse. If you are within 30m of a previously prepared route, it will be offered to you.

**Comment by McDonne11** [comment]
Sorry. Now I understand it.

**Comment by skiselkov** [comment]
No worries, glad I could clear it up.
