### ISSUE TITLE
Cannot see aircraft through glass on tug

### ISSUE THREAD

**Issue by Jimbow1995** [skiselkov/BetterPushbackC#21]
The aircraft is not visible through the glass of the tug. Image is attached
![b733_40](https://user-images.githubusercontent.com/10096828/28336343-7a96551e-6bf9-11e7-9234-f5987c47439d.png)

**Comment by skiselkov** [comment]
This is unfortunately a problem in X-Plane's rendering engine, so there's nothing I can do to fix that, sorry.
