### ISSUE TITLE
X-plane 11 crash V0.16

### ISSUE THREAD

**Issue by muldermatthijs** [skiselkov/BetterPushbackC#22]
I planned a pushback route and the plugin acknowledges my plan. After a couple of minutes, starting APU etc. I pushed a button on my joystick, which is bound to the "start betterpushback" command. At that moment X-plane 11 crashes.

In the log.txt the last lines are:
2017-07-18 21:47:45 acfutils[bp.c:515]: assertion "bp.tug != ((void *)0) || slave_mode" failed: 
Backtrace is:
0 0000000028021A4C
1 0000000028011B5D
2 0000000180005BEC
3 0000000180006338
4 00007FF75FD36903
5 00007FF75F94D3D4
6 00007FF75FD45665
7 00007FF75FD43A35
8 00007FF75F71E642
9 00007FF75F8250BA
10 00007FF75FF3C0D7
11 00007FF75F72008C
12 00007FF7600E5557
13 00007FFAA9282774
14 00007FFAAA2F0D51

[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1157127/Log.txt)

**Comment by skiselkov** [comment]
Thanks for the bugreport, I've got a fix in the works. Should be available shortly.

**Comment by skiselkov** [comment]
Should be fixed in v0.17. Please test.

**Comment by muldermatthijs** [comment]
I will test it later today, let you know the results

**Comment by muldermatthijs** [comment]
Can't reproduce it anymore! Thanks for the fix.

**Comment by skiselkov** [comment]
No need to thank me, this was a stupid mistake on my part :) cheers
