### ISSUE TITLE
FlyJSim Bombadier Q-400

### ISSUE THREAD

**Issue by topofthestack** [skiselkov/BetterPushbackC#223]
Greetings and many thanks for producing this great program,

I've just done two different push-backs at EGBB of a Fly-Be Q-400 on the apron using X-Plane 11.20 and each time the guy doing the push-back has done the job, but refused to speak to me!

Is it something that I've said, or is he always as miserable as this?

Regards.

TERRY

**Comment by tobymutz** [comment]
This has happened to me a few times.
Check the radio volume slider in Settings > sounds

**Comment by topofthestack** [comment]
Many thanks.

TG
