### ISSUE TITLE
BetterPushback and Zibo mod issue

### ISSUE THREAD

**Issue by WebMaximus** [skiselkov/BetterPushbackC#227]
Noticed with the latest versions of the Zibo Mod 737-800 how the pushback starts shortly after being asked to release the parking regardless if the parking brake is released or not.

It's also discussed over here ->

https://forums.x-plane.org/index.php?/forums/topic/150799-betterpushback-and-327/

**Comment by davwheat** [comment]
Issue was an error in the Zibo mod braking code. It has been fixed now. Issue can be closed.

**Comment by WebMaximus** [comment]
That's great news!
