### ISSUE TITLE
Is this forum monitored by developer??

### ISSUE THREAD

**Issue by martinlest** [skiselkov/BetterPushbackC#228]
I have one or two issues, but there doesn't seem much point posting further problems here as most of those already on the forum seem to be without an answer. :-(

 Is the developer still active with this plugin and/or on this forum? (Hope so as I have come to rely on it in X-Plane!).

**Comment by skiselkov** [comment]
I am here, I read the issues, but I'm currently super busy finishing a commercial aircraft product. Once that's one, I'll get back to BP and tie up all the loose ends.

**Comment by martinlest** [comment]
Great - I am really happy to hear that, as for me this is a 'must have' plugin! (Pity it doesn't work with all aircraft -  I'll look back again every couple of weeks and hope you will have time to sort some of this stuff out.. Thanks.
