### ISSUE TITLE
No vision in extreme fog

### ISSUE THREAD

**Issue by thagreenkronic** [skiselkov/BetterPushbackC#23]
I know this isnt really an issue with the addon, but I didnt know where else to put this. When in extreme fog and I try to plan a pushback, I cant see literally anything except my cockpit windows, leading me to guess where the taxi line is. Perhaps giving us the option to zoom in and out during planning would solve this issue? Thanks for your hard work, this is the best pushback plugin for any sim, not just xplane.

**Comment by skiselkov** [comment]
You can already zoom in and out using the standard X-Plane forward/backward commands (the "," and "." keys by default, but you can rebind them to any key or joystick button). However, I'll put in some workaround logic that temporarily bumps the visibility higher while in the pushback planner. That way you will be able to see your plan clearly, but retain the low visibility when you reenter the cockpit.

**Comment by skiselkov** [comment]
Implemented automatic vision increase during planning in v0.17. Please test.

**Comment by thagreenkronic** [comment]
Amazing speed, will test and report back :)

**Comment by thagreenkronic** [comment]
I tested  in all types of weather and I could see my aircraft perfectly at all times. Also using "-" "+" does work to zoom. Thank you!

**Comment by skiselkov** [comment]
Thanks for testing.
