### ISSUE TITLE
Plugin not working at all for me

### ISSUE THREAD

**Issue by MarusarilliuS** [skiselkov/BetterPushbackC#250]
Using clean version of XP-11. Installed zibo mod and BetterPushback plugin. Plugin shows in plugin manager but you can't tick it to enable it. All other plugins can be enabled.
Using steam version of XP-11. Tried both stable and beta branch. Using latest version of plugin.

Any ideas why this is happening?

**Comment by GuillermoRego** [comment]
I have the same problem. I only installed Better Pushback, I didn't install any other plugin. I've tried everything but nothing seems to work.

**Comment by GuillermoRego** [comment]
I realized my folder had a strange letter, it was named 'Informática'. I changed it to 'Informatica', without the 'á' letter and now it all works. Maybe that's your case too?

**Comment by MarusarilliuS** [comment]
Thanks for the reply mate. Checked that but there is nothing of that name in my folder.

**Comment by skiselkov** [comment]
Please download the plugin from the "Releases" section, not the "Clone or Download" button on the main project page. Instructions are now included on the page.
