### ISSUE TITLE
Better Pushback and Trackpads

### ISSUE THREAD

**Issue by NikosPeri** [skiselkov/BetterPushbackC#254]
Perhaps a stupid question, but I haven't found the answer despite searches:
How can you turn your plane is you don't have a mouse wheel and instead are using a trackpad on a Mac?

**Comment by skiselkov** [comment]
The two-finger swipe up or down on a Mac trackpad generates the mouse wheel (same gesture you use to scroll a web page).

**Comment by NikosPeri** [comment]
Ahah... that was indeed simple enough. Thank you.

**Comment by skiselkov** [comment]
My pleasure.
