### ISSUE TITLE
Error 198

### ISSUE THREAD

**Issue by YYZ342** [skiselkov/BetterPushbackC#256]
This is the first time I experienced error 198. 
BetterPushback[acf_outline.c:198]: Error parsing acf file: property _wing/15/_Croot not found

It happened mid flight with Zibo 3.33g. Which is strange on its own as I was not using BP. I did use it while pushing back earlier. When did it happen: while working FMC to change ALT as soon as I entered new ALT the sim crashed. This was the last entry in the log book.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/2872306/Log.txt)

**Comment by skiselkov** [comment]
Please ignore. This is harmless.
