### ISSUE TITLE
IXEG 737-300

### ISSUE THREAD

**Issue by staffguy1** [skiselkov/BetterPushbackC#27]
twice during pushback out of no where the aircraft will just launch up into orbit no warning not sure why or how to fix it

**Comment by staffguy1** [comment]
so I did a test and it looks like if you start the IXEG engines on push back it throws you in the air but if you leave them off the pushback works normally am I missing something or is that a bug

**Comment by skiselkov** [comment]
Can you please detail why you closed this? I wanted to take a look.

**Comment by staffguy1** [comment]
it was due to me being not very smart I was starting both engines at once and apparently it didn't like that very much

**Comment by skiselkov** [comment]
That shouldn't cause you to launch into the air anyway :) I'll check it out to see if I can repro.

**Comment by staffguy1** [comment]
ok odd because it didn't even if I didn't activate pushback I then started both engines together with the Saitek switch panel config I put together at the get I was launched I then took out the modification I did for the Saitek switch panel to start both engines together started them and I wasn't launched into the air

**Comment by skiselkov** [comment]
That's a really odd behavior. Can you make a video of it? At no point should BetterPushback be launching you into the air or anywhere. The only directions in which it applies forces to the aircraft is laterally. It doesn't override the X-Plane physics model, nor does it attempt to do anything out of the ordinary.

**Comment by staffguy1** [comment]
that's why like I said I didn't do a pushback I did a engine start from the gate and it still launched me in the air so then I determined it was the aircraft and not the pushback plugin at first I was thing maybe for some reason I was going from no power to full and having it do some weird stuff but I didn't even turn it on and it still launched me so that's why I closed it I figured it wasn't the pushback plugin

**Comment by skiselkov** [comment]
Thanks for the clarification. Hope you can get your config sorted then.

**Comment by staffguy1** [comment]
no worries hey where do we make suggestions
