### ISSUE TITLE
Compatibility with the Dash 8 Q400

### ISSUE THREAD

**Issue by RemiJL** [skiselkov/BetterPushbackC#275]

**Comment by RemiJL** [comment]
I know it's been mentioned before but the must be a way to solve this issue with the swerving/sliding effect while pushing the plane.  The tug doesn't seem to find the right track or curve and it keeps going from left to right at max angle and I can't stop it unless I use the parking brakes.  Only then it stops with an error saying the plane does not appear to have a steerable gear!  It can't be due to icing on the tarmac as it's summer time and dry.  BP works fine with the ZIBO mod although it uses a larger tug truck!
Is there any way this can be fixed? Or is it the way FlyJsim degined the plane (which I doubt)?
Thanks for the nice and useful plugin!

**Comment by skiselkov** [comment]
I'll have a chat with Jack from FlyJSim and see what we want do on their end. This is something I can't fix in BP, so I'll close this issue for now. The fix, if necessary, will come from FlyJSim.
