### ISSUE TITLE
Plugin is defective for me

### ISSUE THREAD

**Issue by Justefans94** [skiselkov/BetterPushbackC#280]
I downloaded the file, extracted it, and put it into my plugins folder in the resources file for xplane11. I started xp11 and looked at the plugins menu and it doesn't appear in the game. i think that better pushback needs to be fixed or updated so i don't have this problem

**Comment by kecso2009** [comment]
I didnt see it too

**Comment by N1EL** [comment]
I have this too now, use to work great, but now missing from the Plugin list,
It is on the disable / enable list but the box is unticked and can not be ticked,

**Comment by skiselkov** [comment]
Use the "Releases" section to download the plugin, not "Clone or Download" from the main project page.
@N1EL Without a Log.txt, I can't help you.

**Comment by Justefans94** [comment]
Where is the releases section?

**Comment by skiselkov** [comment]
https://github.com/skiselkov/BetterPushbackC/releases

**Comment by Justefans94** [comment]
Ok thanks and which one is it?

**Comment by skiselkov** [comment]
Topmost version is most recent. Click "Assets" and download BetterPushback.zip

**Comment by Justefans94** [comment]
Thanks i finally got it in the game
