### ISSUE TITLE
Better Pushback is not in plugins ingame

### ISSUE THREAD

**Issue by M3TRIX12** [skiselkov/BetterPushbackC#283]
Better push-back is in the files in plugins but does not appear ingame plugins so i cant enable it.

How can i fix it i really want the plugin!

**Comment by skiselkov** [comment]
Please read this: https://github.com/skiselkov/BetterPushbackC/blob/master/README.md

**Comment by M3TRIX12** [comment]
Yes but i already did that but it still doesn't work

**Comment by skiselkov** [comment]
Please attach the Log.txt from your simulator.

**Comment by M3TRIX12** [comment]
Where is that?

**Comment by M3TRIX12** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3799662/Log.txt)

**Comment by skiselkov** [comment]
This can't be the complete file, but let's ignore that for now. Can you screenshot your file explorer showing the contents of ``Resources/plugins/BetterPushback``?

**Comment by skiselkov** [comment]
The folder should contain the following items: ``64``, ``COPYING``, ``data`` and ``objects``. Nothing more, nothing less.

**Comment by M3TRIX12** [comment]
![Capture](https://user-images.githubusercontent.com/57261458/68059235-abbc2f00-fcf3-11e9-9881-7b1792127bb1.PNG)

**Comment by skiselkov** [comment]
Ok, rerun X-Plane and load into an aircraft (any aircraft will do). Then exit and send the Log.txt it generated. The file you sent previously wasn't complete (it wasn't loading any plugins at all).

**Comment by M3TRIX12** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3799842/Log.txt)

**Comment by skiselkov** [comment]
You didn't load up an aircraft

**Comment by M3TRIX12** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3800335/Log.txt)
I ran the game this time

**Comment by skiselkov** [comment]
You keep on sending the same ``Log.txt`` generated on Thu Oct 31 10:38:57 2019. Also, in that log, you were starting up Plane Maker, not X-Plane. Are you sure you are sending the right file and not some copied version from some other folder? The log file should reside at ``C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Log.txt``.

**Comment by M3TRIX12** [comment]
![Capture](https://user-images.githubusercontent.com/57261458/68070569-17d87a80-fd68-11e9-9ad1-4755e1b3a462.PNG)
Do i do anything to this to fix it?

**Comment by skiselkov** [comment]
Don't change any of those settings. Simply run the **simulator** (``X-Plane.exe``) and then send the ``Log.txt`` that was generated in the simulator's installation directory. You keep on sending some old version of the file from Thursday and you didn't run X-Plane in that file, you ran **PlaneMaker**. You need to run X-Plane and send the Log.txt from its run.

**Comment by M3TRIX12** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3800471/Log.txt)
Ok im so sorry

**Comment by skiselkov** [comment]
```
2019-11-02 12:49:10 BetterPushback[xplane.c:539]: This is BetterPushback-v0.47 libacfutils-(null)
Loaded: C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/BetterPushback/64/win.xpl (skiselkov.BetterPushback).
```
Seems the plugin loaded up just fine. How did you determine it doesn't work?

**Comment by M3TRIX12** [comment]
![Capture](https://user-images.githubusercontent.com/57261458/68071883-0e0a4380-fd77-11e9-94b1-f9eba8c85280.PNG)
when i open it on steam its not there but when i open it through x-plane.exe in the files it says i need to update some airfoil so i dont know if it works and i dont know how to update the airfoil of the zibo 737

**Comment by skiselkov** [comment]
That means your Steam install of X-Plane is located somewhere else. X-Plane rewrites the ``Log.txt`` file **every** time it runs. So if it's not writing a new ``Log.txt``, it must be installed somewhere else.

**Comment by M3TRIX12** [comment]
Ok better pushback works now thank you so much and i got a question about somthing else do you know why when i look around with muse its fine but when i use controller my camera locks in forward position?

**Comment by skiselkov** [comment]
@M3TRIX12 I assume you mean when planning the pushback. During that phase, we are using some special camera controls that may not be compatible with controller inputs. So use the mouse in that case. Once you are done planning your pushback, your view should work again as normal.
