### ISSUE TITLE
Sliding Pushback

### ISSUE THREAD

**Issue by AJonesieee** [skiselkov/BetterPushbackC#29]
So I believe this is due to the taxiway and runway being wet, since I hadn't had this issue before, but when I was pushing back, it was sliding all over the place and couldn't go straight. 

Keep up great work :) 
Thanks

**Comment by skiselkov** [comment]
Can you perhaps make a video of this? That would me pinpoint the source.

**Comment by AJonesieee** [comment]
I can see what I can do! I'm just busy at the moment, but I'll within next
few days

**Comment by skiselkov** [comment]
Closing due to lack of movement on this. Reopen if you'd like to continue analysis of this issue.
