### ISSUE TITLE
better push back problem

### ISSUE THREAD

**Issue by indo1994josetorres** [skiselkov/BetterPushbackC#292]
i have problems with the better push back it tells me thatthe audio is no compatible it sends me to download it again ago and tells me the same thing that means

**Comment by Stefanezio** [comment]
i have the same problem as well...

**Comment by PKL123** [comment]
Me too

**Comment by jc55jc** [comment]
Issue with BP v0.48. After push Back, tug never disconnects from aircraft.
Please advise.
Thanks

**Comment by McShiggity** [comment]
Same isssue here, Tug never disconnects which makes nose steering unusable.

**Comment by indo1994josetorres** [comment]
> Yo también tengo el mismo problema...

Ya lo arregle es súper simple cuando abres el simulador y vas activar el Push back lo que tienes que hacer es meterte en la configuración y cambiarle el idioma ya que el idioma predeterminado se desactualiza pero tienes la opción de ponerle mismo idioma pero de otro componente y así le volverá a funcionar acuérdense abrir simulador como si fueran hacer un vuelo normal Y dónde está el Push back le cambian el audio y volver a la normalidad

**Comment by cormac14** [comment]
I have v0.48 if better pushback for xplane and I am using Vulkan but when I click plan pushback my mouse won’t work. It won’t let me scroll to turn the pushback plan plane and it won’t let me place where I want to go.
