### ISSUE TITLE
Faster pull-forward speed

### ISSUE THREAD

**Issue by nriddell** [skiselkov/BetterPushbackC#30]
When I plan a pushback that includes a "pull-forward" element, the speed for the pull-forward is much quicker than the pushback. I have no working knowledge of the real pushback / tow process but it feels like the speed for a pull is much quicker than it should be. I can provide a few metrics on the speed I experience when going back and when getting pulled forward if that is useful. From a simplistic view, could the pull-forward speed be matched to the push back speed?

**Comment by skiselkov** [comment]
What you are describing isn't a bug, it's a feature. Currently the pushback is limited to approximately 1m/s or about walking speed, whereas towing is limited to 4m/s or about jogging speed. It's far easier to go faster when looking ahead - much better visibility. This is pretty normal and even a little bit on the conservative side. Tugs have enough horsepower to actually go pretty quick: 
[![IMAGE Aircraft towing Boeing 747-400 PH-BFE](https://img.youtube.com/vi/2YqkfIDSxGo/0.jpg)](https://www.youtube.com/watch?v=2YqkfIDSxGo)

**Comment by nriddell** [comment]
Thanks for your clear response. I really wasn't sure and so thought it was better to check with you but I didn't have another way to communicate. It makes perfect sense when you explain it like that. As an aside, is there a way that I can support you in your development through a donation of some sort? The time and effort you are putting into this is incredible and it would be wonderful to be able to support you even in this alpha stage. Keep up the great work.

**Comment by skiselkov** [comment]
There's more important things than money. The best way you can support me is by testing & reporting if you run into trouble.

**Comment by nriddell** [comment]
You are a gentleman. I will test as often as I can with your new releases and feedback as much as I can. Best wishes
