### ISSUE TITLE
unable to enable BetterPushback XP11

### ISSUE THREAD

**Issue by EDLWYam** [skiselkov/BetterPushbackC#300]
Hello, 

I am out of ideas.. As you can see in the Toppic I am unable to enable BetterPushback. I have downloaded the correct Zip file and installed it into XP11/Ressources/Plugins folder.

An reinstallation of Xplane doesnt fixed the Problem. Please help me finding the Issue.

Thanks
![xplane_pluginadmin](https://user-images.githubusercontent.com/63298332/78672569-1eec5180-78e1-11ea-8624-2462ffda00a8.PNG)
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/4444465/Log.txt)
![plugins](https://user-images.githubusercontent.com/63298332/78672589-2875b980-78e1-11ea-9e65-0d74302abd42.PNG)

**Comment by ShaneD-VPA** [comment]
ensure your sound system is initialized, I get this if my bluetooth headphones aren't turned on

**Comment by EDLWYam** [comment]
WTF, that was the Problem... how crazy ist this?
Thank you very mutch!!!
