### ISSUE TITLE
Sorry, but 4.8 is a disaster. Please re-do?

### ISSUE THREAD

**Issue by martinlest** [skiselkov/BetterPushbackC#303]
Firstly, as others have noted, the user aircraft no longer follows the track set in the setup.. although the general shape of the pushback path is right, my a/c is way off and ends up on grass (or whatever). 

And the issue of clouds brought up before (as soon as you start pushback planner, cirrus clouds in XP11 weather change to cumulus, and it has been like this for a long time now) has not been fixed.

Please look at this again skiselkov.. I would HATE to be without this plugin, but it's virtually unusable now (the clouds I can reconfigure; the mistakes in pushback path I cannot, of course).

I'd go back to 4.7, which was great - only it doesn't work in XP11.50 :-(  

Hate to complain about freeware, but this great plugin really needs to work properly - so many people have come to rely on it now! Thanks.

**Comment by skiselkov** [comment]
I appreciate the bugreports, but please don't pile several issues into a single bugreport. Report them separately: one for the pushback path following issue, one for the clouds.

**Comment by martinlest** [comment]
Ok, sorry. Thank you for replying so quickly. I'll just use BP as a straight pushback (no turns to the left or right) and look forward to the fix! :-)

**Comment by skiselkov** [comment]
No, you're misunderstanding. I need you to file the two issues you described separately and also in A LOT more detail. Which aircraft? Which airports? Which gates? Screenshots of the planned routes and video of what the pushback ended up actually looking like. Exterior views for what the tug was doing, etc. Without this info, all I'm hearing is "doesn't push the way I want it to", but every time I test it, it does work the way it should. So, we need to figure out exactly WHAT issues you are having and why.

**Comment by martinlest** [comment]
Oh, OK. I will redo the flight I just made and post in this thread as much detail as I can, but none of the attempts I have made so far with 4.8 have had the a/c follow the track shown in the pushback planner. I'll open a new issue for the clouds, though I did do that once before.

**Comment by martinlest** [comment]
OK, will do... thing is though these same airports and aircraft always worked with no problem in 4.7 - never once had a plane not follow its pushback path. Now I haven't had one gfo right yet. Will try to post full details.
