### ISSUE TITLE
Pushback not starting with ZIBO 737-800X

### ISSUE THREAD

**Issue by neelbagora** [skiselkov/BetterPushbackC#309]
Once the pushback tug connects to the zibo 737, deactivating the parking brake does not start the pushback and it just stays there. I have tried disengaging parking brake a few times and using it through the zibo tablet but had no luck.

**Comment by neelbagora** [comment]
Using X-Plane 11.41, ZIBO- 3.40.5

**Comment by rafaeldamasceno** [comment]
I can also verify this problem happens in the ZIBO aircraft, with the latest 11.50b17 and ZIBO 3.42.25. The YAW nose wheel setting is also applied in my case.
