### ISSUE TITLE
Doesn't disconnect

### ISSUE THREAD

**Issue by Shain98** [skiselkov/BetterPushbackC#31]
After pushback when you get the message saying to set the parking brake nothing happens. For a second I thought it's an issue with FF A350 but I checked and it also happens with the default 747. Cheers

**Comment by DennisBeLike** [comment]
Hi, im having the same problem with the b738X zobi mod on xplane 11...the pushback works, but at the time the driver asks to put the parking brake, nothing happens, and i can even stop the pushback. Is there any solution?

**Comment by Shain98** [comment]
DennisBeLike, in case of Zibo's 737 it's an issue with the aircraft, not the plugin.
Here's the hotfix Zibo: http://forums.x-plane.org/index.php?/forums/topic/111305-boeing-b738-800-modified/&page=382#comment-1213492

**Comment by skiselkov** [comment]
@DennisBeLike As @Shain98 noted, the Zibo mod broke the compatibility in one of the recent updates. Please consult the link for details on how to fix this.
@Shain98 Thank you for helping out.

**Comment by DennisBeLike** [comment]
I already fix it, thank you! But now i just notice that the tug is not turning...i dont know why. Safe Flights!
