### ISSUE TITLE
My game crashes after installation

### ISSUE THREAD

**Issue by KasperKoll14** [skiselkov/BetterPushbackC#318]
I just downloaded your betterpushback plugin. Every time I open X-Plane it crashes on "Will Initianize Plugins" I have tried uninstalling it but it still does the same thing.

**Comment by skiselkov** [comment]
No Log

**Comment by KasperKoll14** [comment]
What?

**Comment by pilotflores91** [comment]
I get the same thing too. No Log file X-Plane only loads when I remove the BetterpushBack folder from my plug-ins. Was working fine before now idk what happent.
