### ISSUE TITLE
Adding Polish translations

### ISSUE THREAD

**Issue by MishutkAviation** [skiselkov/BetterPushbackC#322]
Hello,
I want to create a Polish message set (en-pl and pl), can someone tell me how to edit recordings to add radio-like sound effects? I use Audacity for sound editing, maybe there's some option in that program?

**Comment by skiselkov** [comment]
I already e-mailed you that you should just record it clean. I'll add the radio effects myself.

**Comment by MishutkAviation** [comment]
I wrote you an email, I have all the recordings
