### ISSUE TITLE
ixeg 737-300 no tug

### ISSUE THREAD

**Issue by andre6991** [skiselkov/BetterPushbackC#34]
When i select start push back in the IXEG 737-300 is says push back failed no suitable tug available can you help me? it seem like i'm the only one having this problem
thank you very much 
(i'm using the latest version)

**Comment by andre6991** [comment]
actually i think it does that with every airplane

**Comment by skiselkov** [comment]
I just did a test with the IXEG 737 and it works perfectly well. I think you may have installed it incorrectly or something. Make sure you only have the *one* "BetterPushback" folder in `Resources/plugins` (doesn't matter if the folder has a suffix like "`-0.21`", but it's important there's only one). Also, can you please look inside the plugin under `objects/tugs` and verify that you have these two subfolders there: `AST-1X.tug` and `AST-3F.tug`. This is where BP looks for its tug models and these tugs currently come with the plugin (AST-1X for wide body airliners, AST-3F for narrow body and regional airliners). For the IXEG 737, BP should be selecting the AST-3F model.

**Comment by andre6991** [comment]
thank you for the qick response i dont' know what's wrong the plug in is installated in the correct folder and the tug are there. i can plan the route and everything but when i say start push it doesn't work 
i confirm it does the same thing even with the default 737

**Comment by skiselkov** [comment]
I'll prepare a build for you which has more analytics enabled to determine why it's not finding a suitable tug. Are you using Windows, Mac or Linux? So I know which version to build for you.

**Comment by skiselkov** [comment]
Just out of curiosity, can you please attach your Log.txt.

**Comment by andre6991** [comment]
i'm using window 10 64 bits 
and this is my log file i hope you find somenthing that can help you 
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1166867/Log.txt)

**Comment by skiselkov** [comment]
As I suspected, the problem isn't that the tug can't be found. There's a problem with the audio subsystem - BetterPushback is having trouble loading the tug's sounds. Let scratch my head some more, maybe I can come up with a solution.

**Comment by skiselkov** [comment]
I've built a test version for you, just so I know how to address this. The ZIP doesn't contain a full plugin, only one file from the plugin. Please replace the file in `64/win.xpl` with it. If it still doesn't help, please send me the Log.txt it generated.
[win.xpl.zip](https://github.com/skiselkov/BetterPushbackC/files/1166915/win.xpl.zip)

**Comment by JetNoise61** [comment]
Hi, 
first of all: a million thanks for this plugin. Best i have seen EVER! ;-)
Testing the IXEG and "Connect first" via JStick pushbutton & dataref (lua script) results in a "pushback failure, please tell me where ...." 

Doing this through the XP-plugin-BetterPushback menue (on screen/ "connect first" button works instead. Strange ;-)

**Comment by skiselkov** [comment]
@JetNoise61 The issue you describe is different, please open a new ticket for it and put your comment into the description. This is a bug tracker, not a discussion forum, you can't just append comments arbitrarily.

**Comment by andre6991** [comment]
i fixed it thank you very much for your help.
the problem was obviously on my end and not yours so i'm sorry i had you lose time fixing something that's not your fault. 
to fix it i download  the latest audio driver and cleaned my registry
thank you very much for this amazing plugin and i'm sorry

**Comment by skiselkov** [comment]
No worries, glad you got it resolved.
