### ISSUE TITLE
A350 no disconnect and no push

### ISSUE THREAD

**Issue by Milki52** [skiselkov/BetterPushbackC#35]
Hey,

first big thanks for this wonderful plugin. At my last flight i flown with the ff350 and at EDDM the push starts but ends after 20m no voice any more i had to deactivate the plugin via the Plugin Admin. After landing at EDDH i want to start back to EDDM and again the push starts and after a few meters it kills it again. I restartet the Plugin and try a tow, that worked very well but after reaching the end of the planned route the truck didnt disconnect. Parkingbrake was set.

Any solution? :D

**Comment by skiselkov** [comment]
I'll try to talk to FlightFactor and get a hold of the A350 to test. I don't have the FF A350 yet, so I can't test it right now, but I'll keep the issue open so I don't forget.

**Comment by gharac** [comment]
Affirm this Bug. Truck will not disconnect, p/b worked well (for me)

**Comment by weslley-pereira** [comment]
No problem here.
X-Plane 11.02r2
FF a350 v1.4.6

**Comment by Milki52** [comment]
by me A350 V1.4.6
XP 10.51

**Comment by gharac** [comment]
my setup
FF a350 v1.4.6
X-Plane 11.02r2
(no disconnect of the tug)

**Comment by weslley-pereira** [comment]
After 6 tests 3 with energy and 3 without energy, I noticed that the tug does not disconnect when the aircraft is energized.

With the aircraft completely without power the tug works 100%, my previous tests were being carried out this way.

**Comment by skiselkov** [comment]
@weslley-pereira While I'm waiting to get access to the aircraft, maybe you can help me out to get this fixed earlier, by gathering some information for me instead. I need you to get a plugin called DataRefTool and get me the values of some datarefs in particular. The procedure to download and install DataRefTool as well as how to look up datarefs is detailed here: https://github.com/skiselkov/BetterPushbackC/issues/4 . Into the search field of DataRefTool, please type "park". Then start the pushback and come to the point where it asks you to set the parking brake after finishing pushback. Try to set the parking brake and then take a screenshot of the DataRefTool window. I need to see what happens to the parking brake dataref values. Maybe the aircraft is using a custom parking brake dataref when it is powered up and my plugin needs to check something other than the default `sim/flightmodel/controls/parkbrake`.

**Comment by Milki52** [comment]
Its sounds like the same problems as with the Ground Handling with this bird. This disappears also when something changed with the APU or ext. Power.

**Comment by weslley-pereira** [comment]
Here it is, I had several problems with DataRefTool, so I used DataRefEditor.
Follow the print

![a350_xp11_80](https://user-images.githubusercontent.com/27384771/28502300-cb0c2f26-6fc5-11e7-824c-23be0ee59540.png)
![a350_xp11_78](https://user-images.githubusercontent.com/27384771/28502301-d2103a92-6fc5-11e7-8a4f-41f0fab1cd23.png)
![a350_xp11_79](https://user-images.githubusercontent.com/27384771/28502304-d8351550-6fc5-11e7-86af-8d6a83385591.png)

**Comment by weslley-pereira** [comment]
Tug working perfectly with BetterPushback-0.23

![a350_xp11_82](https://user-images.githubusercontent.com/27384771/28534628-b59b2bbc-7077-11e7-9033-0ed82cd0962d.png)

![a350_xp11_81](https://user-images.githubusercontent.com/27384771/28534612-ad5d38f0-7077-11e7-8722-f31d53f1fdcd.png)

**Comment by Milki52** [comment]
i can confirm it. Works good on 10.51 with 0.23 :) thanks a lot

**Comment by skiselkov** [comment]
Yep, just confirmed that myself on the A350 as well. Thanks for reporting and closing this issue now.

**Comment by darkroby** [comment]
> Tug working perfectly with BetterPushback-0.23
> 
> ![a350_xp11_82](https://user-images.githubusercontent.com/27384771/28534628-b59b2bbc-7077-11e7-9033-0ed82cd0962d.png)
> 
> ![a350_xp11_81](https://user-images.githubusercontent.com/27384771/28534612-ad5d38f0-7077-11e7-8722-f31d53f1fdcd.png)

how can i download the v0.23?
