### ISSUE TITLE
FlightFactor 767 compatibility

### ISSUE THREAD

**Issue by rickw844** [skiselkov/BetterPushbackC#37]
BetterPushback doesn't seem to work on my Flightfactor 767, but does work on the default 737 in X-Plane 11.  Am I doing something wrong?

Thanks.

**Comment by skiselkov** [comment]
You're not doing anything wrong, the FlightFactor aircraft are incompatible and don't let BP take control of the steering. I'm talking to FlightFactor to get the issue resolved in a future update to the aircraft.
