### ISSUE TITLE
dataref "connect_first"  v 0.21

### ISSUE THREAD

**Issue by JetNoise61** [skiselkov/BetterPushbackC#38]
Hi,
first of all: a million thanks for this plugin.
Sorry for wrong use of Github system initially.

Testing the IXEG and "Connect first" via JStick pushbutton & dataref (lua script) results in a "pushback failure, please tell me where ...."

Doing this through the XP-plugin-BetterPushback menue (on screen/ "connect first" button works instead. Strange ;-)

Windows10, X-Plane 11.02r2 (build 110202 64-bit), 

[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1167353/Log.txt)

**Comment by skiselkov** [comment]
No worries. Thanks for the bug report. I'll post a fix shortly.

**Comment by skiselkov** [comment]
Should be fixed in release 0.22, please test.

**Comment by JetNoise61** [comment]
hello, 
what a quick fix !!
I tested on three occasions (via DATAREF, LUA, JOYSTICK ) and it works now as expected. I love it. Thanks
Have a nice weekend !!

BTW, if you need me for testing on the IXEG, FF757, PMDG DC6,  FF767 (friend) let me know.
Oliver
