### ISSUE TITLE
A320 Jardesign

### ISSUE THREAD

**Issue by Enix0** [skiselkov/BetterPushbackC#4]
If  I try to pick Pre-Plan Pushback it says:,, Pushback failure: aircraft has non-positiv wheelbase . Sorry, tail draggers aren´t supported.
What can I do?
Sorry for my bad English...

**Comment by skiselkov** [comment]
Unfortunately I don't have the JAR A320, so I can't debug this myself. I need some more information from you. Please download an addon called DataRefTool (https://github.com/leecbaker/datareftool/releases). From the menu then select Plugins -> DataRefTool -> View Datarefs (see screenshot 1). In the window that pops up, put "tire_z_no_deflection" into the black area next to "dat" (see screenshot 2) and click on the right hand side after the '=' that comes up. I need to see the first three values. Repeat the same process and put "acf_gear_steers" into the search field (see screenshot 3). Please copy values after the "=" and send them to me.
This information will help me. Thanks.

**Comment by Enix0** [comment]
1. tire_z_no_deflection : [-11.240056,1.357143,1.357143,-16.309847,-16.309847,-16.309847,-16.309847,-16.309847,-16.309847,-16.309847]

2. acf_gear_steers :
[1,0,0,0,0,0,0,0,0,0]

Is this that what you wanted? :)

**Comment by skiselkov** [comment]
Yes, thank you.

**Comment by Enix0** [comment]
Ok, nice that you´re so fast :dagger:

**Comment by skiselkov** [comment]
Could you please get one more value for me please: acf_gear_type. This is just to validate that the fix I'm working on will help.

**Comment by Enix0** [comment]
Sure here; 
[3,3,3,0,0,0,0,0,0,0]

**Comment by skiselkov** [comment]
Thank you, then my fix will work. I'll prepare a build for you to test shortly.

**Comment by Enix0** [comment]
Yes thank you,

**Comment by Enix0** [comment]
Short question:
If I will do better Pushback at the CRJ200 it says:
Pushback failure: no suitable tug for your aircraft. When is coming one for the Crj200? Next update?

**Comment by skiselkov** [comment]
I'm not sure I will be able to support the CRJ200. Towbarless tractors have a minimum permissible nose gear leg length. This is because the aircraft fuselage must be up high enough so that it doesn't collide with the tractor when the tractor turns. Currently the lowest tractor I have plans for is the AST-3F, which can accept an aircraft with a nose gear leg length of 50cm. I'll see if I can find some way to work around this problem.

**Comment by Enix0** [comment]
Okey thank you,
this Plug-in is really nice.

**Comment by skiselkov** [comment]
Please try build v0.10 to see if it fixes the problem.

**Comment by Enix0** [comment]
Now I can do that Pre- Pushback, but if I click on start Pushback X-Plane Crashes how can I send the log?

**Comment by skiselkov** [comment]
@Enix0 You are running on XP10, right?

**Comment by Enix0** [comment]
Right

**Comment by skiselkov** [comment]
This is a known issue with an incompatibility with XP10. I have a fix for that in hand, will publish shortly. I'll close this issue for now, since I already have an XP10 compatibility issue ticket open.

**Comment by Enix0** [comment]
Yes thank you :)
