### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by skiselkov** [skiselkov/BetterPushbackC#41]
The spoken messages need to be translated into German, as they are currently only available in English. The text of the messages in English is:

* `connected.wav`: "Tow connected and bypass pin inserted. Release parking brake."
* `disco.wav`: "Disconnecting tow. Stand by."
* `done.wav`: "Tow is disconnected and bypass pin has been removed. Have a nice flight."
* `driving_up.wav`: "Ground to cockpit. Tow is driving up."
* `op_complete.wav`: "Operation complete. Set parking brake."
* `plan_end.wav`: "Ground to cockpit. Plan acknowledged, call me through the menu when you are ready."
* `plan_start.wav`: "Ground to cockpit. Please show me where you want to go."
* `ready2conn.wav`: "Ready to connect. Set parking brake."
* `start_pb.wav`: "Ok, all doors and hatches are closed. Starting pushback and you may start engines."
* `start_tow.wav`: "Ok, all doors and hatches are closed. Starting tow and you may start engines."
* `winch.wav`: "Winching strap and adapter in position. Release parking brake when ready to start pushback."

The last message `winch.wav` is a new message that was introduced to support the LEKTRO AP88 tug which uses a winch & strap to pull the nose wheel onto the lift platform instead of lift arms. Video of this can be seen here: https://youtu.be/xinlMfsdDZE?t=1m33s

**Comment by liebbe10** [comment]
`connected.wav`: “Pushback ist festgemacht und Bypass-Pin hineingesteckt. Lösen Sie die Parkbremse”.
`disco.wav`: "Trenne den Pushback. Warten Sie einen Moment."
`done.wav`: “Pushback ist losgemacht und Bypass-Pin wurde entfernt. Haben Sie einen schönen Flug!”
`driving_up.wav`: “Ground to cockpit. Pushback fährt heran.”
`op_complete.wav`: “Push is fertig. Setzen Sie die Parkbremse.”
`plan_end.wav`: “Ground to cockpit. Plan eingereicht. Rufen Sie mich über das Menü, wenn Sie bereit sind.”
`plan_start.wav`: “Ground to cockpit. Bitte zeigen Sie mir zuerst, wo Sie hin wollen.”
`ready2conn.wav`: “Bereit zum festmachen. Setzen Sie die Parkbremse.”
`start_pb.wav`:“Ok, alle Türen und Öffnungen sind verschlossen. Beginne mit dem Pushback. Sie können die Triebwerke starten”
`start_tow.wav`: “Ok, alle Türen und Öffnungen sind verschlossen. Beginne mit dem Schleppen. Sie können die Triebwerke starten”
`winch.wav`: “Winching-Strap und Adapter sind festgemacht. Lösen Sie die Parkbremse sobald Sie bereit sind.”

**Comment by skiselkov** [comment]
@liebbe10 Thank you for the translations. I mislabeled this issue, I also needed somebody who's a native speaker to record them. I'd appreciate if you can help me out with that. Simple mono sound without any filters would be great. I'll apply all the post processing myself. Feel free to ZIP the sounds up and attach them to this issue.

**Comment by liebbe10** [comment]
This are the spoken audacity files
[better pushback audio.zip](https://github.com/skiselkov/BetterPushbackC/files/1171353/better.pushback.audio.zip)

**Comment by liebbe10** [comment]
Very happy to support this amazing plugin :)

**Comment by skiselkov** [comment]
Thank you very much. Sorry to have a bit of a moan about some of the translations, but I'd like to ask if in your opinion we could refine them a bit:
1. “Pushback ist festgemacht und Bypass-Pin hineingesteckt. Lösen Sie die Parkbremse.” The word "Pushback" refers to the operation, not the vehicle. I think it would make more sense to refer to it as "Schlepper", or if you want to get really official, "Schleppgerät". Same thing for the other messages that are talking about the vehicle.
1. "Winching-Strap". I think a good translation of this would be "Windenriemen" or something to that effect. See the video I linked and just think of what you'd call that in German :)
1. Perhaps use some more aviation lingo like "Klar zum anlassen" or "Frei zum start". Feel free to take your inspiration from here: https://youtu.be/0DLrAsade0c?t=10m40s You don't have to copy them word by word, just some suggestions on how to make it sound a little bit more organic :)

**Comment by liebbe10** [comment]
1. Yeah I will change it to Schlepper. (I think I also heard pushback referring to the vehicle)
2. Maybe "Seilwinde"
3. You are absolutely right! Although I'm a native speaker I'm not used to german aviation phrases...but now as you said it, it sounds 100 times better...

**Comment by liebbe10** [comment]
`connected.wav`: “Schlepper ist festgemacht und Bypass-Pin hineingesteckt. Lösen Sie die Parkbremse”.
`disco.wav`: "Trenne den Schlepper. Warten Sie einen Moment."
`done.wav`: “Schlepper ist losgemacht und Bypass-Pin wurde entfernt. Haben Sie einen schönen Flug!”
`driving_up.wav`: “Cockpit für Boden. Schlepper fährt heran.”
`op_complete.wav`: “Push is fertig. Setzen Sie die Parkbremse.”
`plan_end.wav`: “Cockpit für Boden. Plan eingereicht. Rufen Sie mich über das Menü, wenn Sie bereit sind.”
`plan_start.wav`: “Cockpit für Boden. Bitte zeigen Sie mir zuerst, wo Sie hin wollen.”
`ready2conn.wav`: “Bereit zum festmachen. Setzen Sie die Parkbremse.”
`start_pb.wav`:“Ok, alle Türen und Öffnungen sind verschlossen. Pushback beginnt. Triebwerke sind frei zum Start”
`start_tow.wav`: “Ok, alle Türen und Öffnungen sind verschlossen. Pushback beginnt. Triebwerke sind frei zum Start”
`winch.wav`: “Seilwinde und Adapter sind festgemacht. Lösen Sie die Parkbremse sobald Sie bereit sind.”

**Comment by skiselkov** [comment]
1. It's just I've never heard actual ground crew refer to it that way. In English it's the same way. You could refer to it as "pushback", but I've never heard the pros refer to it that way.
1. Sounds ok.
1. I watch a lot of Pilot's Eye :)
1. "Cockpit für Boden" - I think the guy in the video misspoke, he should have used "Cockpit vom Boden" or better yet "Boden zum Cockpit".
1. "Öffnungen" - maybe use "Luken" or something like that. "Öffnungen" sounds too generic (there's a lot of Öffnungen in the aircraft that need to stay open, like the intakes to the engines, etc.).

Btw: "Warten Sie einen Moment." while perfectly correct German, in German aviation lingo "Stand by" is used all the time and it means essentially the same thing. But don't take that to mean that I want you to change the translation - it's fine with the long phrase (not every sim pilot is experienced in aviation jargon).

**Comment by liebbe10** [comment]
Hm...I think "Cockpit für Boden" is a phrase being used (but difficult to find out...in the other pilotseye videos they often use english phrases or simply say "Hello Ground")
Going to use Luken instead.
I'm going to record it tomorrow as I'm already tired :)

**Comment by skiselkov** [comment]
Thank you, sounds great.

**Comment by AirLuSa** [comment]
Hej,
I've have some suggestions for improvement. When I'm doing pushback/ walk out assistance as a ramp agent in german I used to say "Boden an Brücke" instead of "Cockpit für Boden" to get in contact with the cockpit crew. Furthermore I suggest to just say "Bypass-Pin ist gesteckt", because "hineingesteckt" sounds a little bit to formal for me, instead of "Triebwerke frei zum Start" I would suggest to say "Triebwerke frei zum Anlassen". Maybe "Luken" is a better translation for "hatches" and not "Öffnungen", so it would be "Alle Türen und Luken sind zu"

**Comment by liebbe10** [comment]
OK cool thanks :)

**Comment by AirLuSa** [comment]
You're welcome!

**Comment by skiselkov** [comment]
Danke @AirLuSa.

**Comment by AirLuSa** [comment]
I've found some time to record the files. See attachment. While recording I noticed that would like to make a suggestion.  The phrase "Ok, all doors and hatches are closed" of the start_pb.wav/ start_tow.wav should be infront of the ready2conn.wav file. Because in real you would first do the walk around to check the aircraft and then would connect the pushback truck. So the respective phrases should look like this:

ready2conn.wav: "Ok, all doors and hatches are closed. Ready to connect. Set parking brake."
start_pb.wav: " Starting pushback and you may start engines."
start_tow.wav: "Starting tow and you may start engines."

This is the way I did the german translation recordings now. Hope they are in the correct format.

[pushbackaudio.zip](https://github.com/skiselkov/BetterPushbackC/files/1173103/pushbackaudio.zip)

**Comment by skiselkov** [comment]
Thanks! I'll think about restructuring the messages. The reason why it's structured like this is because there can be a lot of time between when the tug attaches & pushback actually starts. This is due to the "connect first" feature, which basically runs the whole procedure up to the actual call for brake release. Some folks requested the ability to attach the tug without specifying a plan and while still waiting for a pushback clearance. That's because sometimes the pushback clearance depends on the direction of the initial taxi and when given clearance, apron expects them to start pushing very quickly (i.e. they didn't want to waste time waiting for the tug to drive up and connect).
Nevertheless, I fully agree you'd not be lifting the aircraft up while somebody's still working on it. I'll think of a way to restructure this.

**Comment by skiselkov** [comment]
Alright, audio is published in the latest release. Please test, check if the volume is good, distortion isn't overdone and overall if it sounds good.

**Comment by AirLuSa** [comment]
For me the sound is okay. But I know what I am saying so maybe some other have to test.

**Comment by Semirben** [comment]
I compared both english and german translations ingame and in my opinion the german translations are a little bit too quiet compared to the original english sound files and therefore sometimes hard to understand from the cockpit.

Tested with default 737 (Zibo Mod)

**Comment by AirLuSa** [comment]
A friend of mine told me, that the german version contains a little bit to much atmospheric noise in his opinion. Maybe you can reduce it a little bit.

**Comment by skiselkov** [comment]
@Semirben I'll prepare a version which is a little bit louder and with less noise.
@AirLuSa Could I ask you if you could record two more messages? I've reworked the "driving away" phase and split up `done.wav` into two messages, depending on which side of the aircraft the tug will be leaving. The English text of the new messages is:
* `done_left.wav`: "Tow is disconnected and bypass pin has been removed, hand signal on the left, we'll see you next time and have a safe flight."
* `done_right.wav`: "Tow is disconnected and bypass pin has been removed, hand signal on the right, we'll see you next time and have a safe flight."

Again, you don't have to translate it word by word and feel free to improvise the last bit of the goodbye message. My shot at translation would be:

* "Schlepper ist getrennt und Bypass-Pin ist gezogen, Handsignal [Links|Rechts], wuensche Ihnen einen Schoenen Flug."

I've also modified the tug driving and animation. The tug actually stops abeam the cockpit for 15 seconds, the driver opens the door and stands by the tug giving a "thumbs up" with one hand and holding the bypass pin in the other, then gets back in and attempts to drive back to the pushback starting position (trying to avoid to get in the aircraft's way).

**Comment by AirLuSa** [comment]
Wow. Nice feature.

Ok: I've translated it to "Der Schlepper wurde entfernt, der bypass-pin ist gezogen. Freizeichen gibt's von der linken/ rechten Seite. Einen angenehmen Flug, Tschüss."  So it's not a word by word translation, but the content is the same.
[done_left_right.zip](https://github.com/skiselkov/BetterPushbackC/files/1180241/done_left_right.zip)

**Comment by skiselkov** [comment]
Sounds good, thanks. I'm still mulling over whether to call it "clear signal" or "hand signal" in the English as well. The former is officially correct phraseology, but the latter is a bit easier to understand and I've heard it used as slang as well. What do you think?

**Comment by AirLuSa** [comment]
Use what you like most.

**Comment by skiselkov** [comment]
Remastered German audio & built in the new clear on left/right messages in v0.29. Please test.

**Comment by AirLuSa** [comment]
Sound good now ;-)

**Comment by skiselkov** [comment]
Thanks for testing. I'll keep this open for a couple more days in case some of the other guys find the audio is still not good enough, then I'll close it.
I readjusted the EQ settings. I had the EQ set to cut off just a bit too much in the 3-4 kHz range and put in too much of the low-frequency rumble, resulting a slightly too booming and muffled voice.

**Comment by JetNoise61** [comment]
I sent you a message about translations in general ;-)
I would use the wording "Hand signal". Most common.
Oliver

**Comment by skiselkov** [comment]
@JetNoise61 Thank you. Saw your message. The best man to talk to about the choice of phraseology would be @AirLuSa, as he's the one who did the translation (and also works as a pushback driver). I'll be happy to include whatever you guys think is the most sensible choice.

**Comment by AirLuSa** [comment]
Well I'm not a pushback driver, but a ramp agent and in this position we sometimes do the walk out assistance while pushback operation and then I'm responsible for the communication during the pushback.

**Comment by JetNoise61** [comment]
Hi, 
I think i have to appologize. 
Was there a different guy speaking the german text initially? 
I tried the (New?) translations today and they are much better. 

To my excuse: I am/was used to listening to gnd operations from the international military side. (Air-Crew) 

Guess civilians are more relaxed ;-) or things have changed in the last 10 years, haha
English is (was) mandatory..... 

Anyway, Alles gut... 

Grüße 
Oliver 


⁣Gesendet mit TypeApp ​

**Comment by AirLuSa** [comment]
No. It was me from the beginning. To my mind Skiselkov just remastered the sound files for better quality.

Well, you are right, the standard language is of course english, but if you have german speaking pilots and a german speaking ground crew, it's common to do the pushback and start up communication in german, there are only a handful pilots which still wish do that in english. So maybe yes the civilian guys are a little bit more relaxed as you said.

**Comment by skiselkov** [comment]
I'll close this one for now. I'll be working on the location-aware voice language selection in a separate issue.

**Comment by skiselkov** [comment]
Can you please translate these new texts for me:
* "Preferences"
* "BetterPushback Preferences"
* "User interface"
* "X-Plane's language"
* "Ground crew audio"
* "My language only at domestic airports"
* "My language at all airports"
* "English at all airports"
* "Save preferences"
* "Ground crew speaks my language only if the country the airport is in speaks my language. Otherwise the ground crew speaks English with a local accent."
* "Ground crew speaks my language irrespective of what country the airport is in."
* "Ground crew always speaks English with a local accent."
* "Save current preferences to disk. Note: restart X-Plane for changes to take effect.

**Comment by AirLuSa** [comment]
"Einstellungen"
"BetterPushback Einstellungen"
"Benutzeroberfläche"
"Ausgewählte Sprache in X-Plane"
"Audio Bodenpersonal"
"Meine Sprache für inländische Flughäfen"
"Meine Sprache für alle Flughäfen"
"Englisch für alle Flughäfen"
"Einstellungen sichern"
"Bodenpersonal spricht meine Sprache, wenn sich der Flughafen in einem Land befindet, in dem meine Sprache gesprochen wird. Falls nicht, spricht sie Englisch mit lokalem Akzent."
"Bodenpersonal spricht meine Sprache, egal in welchem Land sich der Flughafen befindet."
"Bodenpersonal spricht immer Englisch mit lokalem Akzent."
"Aktuelle Einstellungen auf die Festplatte speichern. Hinweis: X-Plane muss neugestartet werden, damit die Einstellungen aktiv werden."

**Comment by skiselkov** [comment]
Thank you very much. One more thing, if possible, could you please record the English messages with a German accent as well? That way the accented versions would be played for non-German pilots when flying in German-speaking countries.

**Comment by AirLuSa** [comment]
Done. :-)
[german_english.zip](https://github.com/skiselkov/BetterPushbackC/files/1197668/german_english.zip)

**Comment by skiselkov** [comment]
Damn you're fast! Thanks!

**Comment by skiselkov** [comment]
Please test english/german audio in v0.37.

**Comment by skiselkov** [comment]
I take it that no complaints = everything is ok.
