### ISSUE TITLE
X-Plane 12 compatibility

### ISSUE THREAD

**Issue by xEtarusx** [skiselkov/BetterPushbackC#412]
Hi @skiselkov,
is it possible that you update this awesome plugin to work with the newest X-Plane 12 version?

The latest version sadly doesn't work anymore in X-Plane 12.

Best regards,
Etarus

**Comment by dualznz** [comment]
i agree it would be awesome to see it in xp12, the default pushback system in 12 is horrible, but as i have seen in the PR's for this project there is still some sitting in there from last year, i am feeling that this beautiful addon has been abandoned

**Comment by xEtarusx** [comment]
@dualznz Well he updated the plugins after the 11.50 Vulkan release to fix incompatibility after a longer inactivity too. So my hope isn't gone yet :)

**Comment by crisk73** [comment]
> Sorry for the question… are you totoritko? The genius behind the CL650?

Yep he's the genius behind many things. lol

**Comment by skiselkov** [comment]
XP12 version is available now.
