### ISSUE TITLE
Better pushback doesn't work anymore x-plane 11

### ISSUE THREAD

**Issue by jongsoft** [skiselkov/BetterPushbackC#428]
Hello Simmers, i've got the same problem , i think after an update. Only in windowed mode better pushback works okay but i've got 3 monitors so there's no windowed mode as a  choice anymore. Is there a solution for this problem? Beter pushback doesn't work in xplane 12 aswell. If i try to start it there's no responce. 

Anyone an idea?
Thanks in advanced
![betterpushback](https://user-images.githubusercontent.com/60671010/196661696-4b3416d1-7030-4b4e-8fbb-dc95a521c2ce.jpg)

Peter

**Comment by Slowe09** [comment]
I have the same issue. Do you have a resolution because it is really frustrating.

**Comment by jongsoft** [comment]
> I have the same issue. Do you have a resolution because it is really frustrating.

i found the problem, if you change the setting of the monitor to window it works perfect. then change back to full vieuw.
