### ISSUE TITLE
CTD on XP12b8

### ISSUE THREAD

**Issue by icecube919** [skiselkov/BetterPushbackC#429]
Sim crashes since update to beta 8 when trying to start better pushback.

Log:
[BetterPushback-v0.49]: Dataref 'sim/weather/use_real_weather_bool' has been replaced. Please use the new name.
2022-10-19 18:37:19 BetterPushback[dr.c:96]: assertion "dr->writable" failed: dataref "sim/weather/use_real_weather_bool" is not writable (bp_cam.c:1200: &drs.use_real_wx)
--=={This application has crashed because of the plugin: }==--
(Art controls are modified.)

**Comment by nubbix** [comment]
Had this just now..  When pressing "Request pushback" Crashed to desktop

**Comment by skiselkov** [comment]
Fixed in commit 81e41f8.
