### ISSUE TITLE
Liveries for AST-3F

### ISSUE THREAD

**Issue by AirLuSa** [skiselkov/BetterPushbackC#43]
Hej,

I've created a few liveries for the AST-3F truck. Please download again the LH LOES livery to fix the conf.file. I accidentally thought they were pushing at Hannover EDDV. 

Globground Berlin for EDDT and EDDB
[GlobeGroundBerlin.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1177907/GlobeGroundBerlin.livery.zip)

Hannover Aviation Ground Services for EDDV
[HAviationGroundServices.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1177910/HAviationGroundServices.livery.zip)

Lufthansa Leos for EDDF, EDDH, EDDL and EDDM
[LEOS.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1177911/LEOS.livery.zip)

and swissport for the airports of Switzerland like LSZH, LSGG
[Swissport.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1177912/Swissport.livery.zip)

Have fun
Lukas

**Comment by skiselkov** [comment]
Thanks for the paints, I've put them. Btw, for future reference, please send me the paints in PNG, not DDS format. The DDS files are automatically generated by my build scripts, but I keep PNGs in the repo (because they're smaller).

**Comment by skiselkov** [comment]
Released in 0.29. Please check if I didn't mess anything up.

**Comment by AirLuSa** [comment]
looks fine... ;)

**Comment by skiselkov** [comment]
Thanks, I'll close this now.
