### ISSUE TITLE
crashe xp 12 data ref issue

### ISSUE THREAD

**Issue by Pilotwillem** [skiselkov/BetterPushbackC#432]
X-plane crashed when ask "start pushback"
txt from log,txt

[BetterPushback-v0.51]: Dataref 'sim/weather/use_real_weather_bool' has been replaced. Please use the new name.
2022-10-22 15:02:33 BetterPushback[dr.c:96]: assertion "dr->writable" failed: dataref "sim/weather/use_real_weather_bool" is not writable (bp_cam.c:1200: &drs.use_real_wx)

**Comment by skiselkov** [comment]
Download the latest build. This has been fixed.

**Comment by Pilotwillem** [comment]
i did yesterday evening, downloaded the wrong version sorry about that. thnx for the quick response
