### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nubbix** [skiselkov/BetterPushbackC#433]
Could you please add a text file in release folder that indicates version number. 
Very suitable for checking which version is the latest.

**Comment by skiselkov** [comment]
This already exists in your Log.txt. BP announces itself as follows:
`2022-10-23 14:36:57 BetterPushback[xplane.c:538]: This is BetterPushback-v0.52 libacfutils-d11c6f4`
This includes the version number.

**Comment by nubbix** [comment]
Thanks.. Just thought it would be easier for people to find as many do not even open that file :) 
Anyway, made one for personal use, just have to remember to update it :)  

Ps. Thanks for your work

![2022-10-23_155544](https://user-images.githubusercontent.com/6438354/197396366-a7b9b20d-7e2f-463c-a637-9d30b3d4537c.jpg)
