### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Jorge-R-Hidalgo** [skiselkov/BetterPushbackC#54]
Someone knows if there is any incompatibility with other addons, I have problems to follow the selected plan, it gets slow and does not turn the plane at any airport ... sorry for my English ... greetings.

**Comment by skiselkov** [comment]
Which airplane are you using? Is it the FlightFactor Boeing 757 or 767? If so, can you make sure you've updated to the latest version of these airplane models via FlightFactor's X-Updater service? FlightFactor released a fix for the incompatibility two days ago.

**Comment by Jorge-R-Hidalgo** [comment]
Hi, skiselkov: The airplane I use to test is the default 737, I have a question, if the plane is cold and dark does the push normally or must be ready to start engines ?, the addons I have installed are JARDesign, X- Life, Ground Handling, FollowMe Car and TugMaster, with some of these addons there is some kind of incompatibility ?.

**Comment by skiselkov** [comment]
The airplane can be cold and dark and the pushback should still function normally. Can you attach your `Log.txt` from when it's behaving incorrectly?

**Comment by Jorge-R-Hidalgo** [comment]
Hi Skiselkov: Fix the problem!!!, delete the X-Plane.prf file in the X-Plane 11\ Output\preferences folder, run X-Plane again and now it works perfectly. Thank you.

**Comment by skiselkov** [comment]
Wow, when in doubt, delete preferences - got it :) Glad you got it sorted.
