### ISSUE TITLE
Request for PB with TU 154M

### ISSUE THREAD

**Issue by birdydma** [skiselkov/BetterPushbackC#55]
New release today. The TU 154M is know friend with XP 11. Did a quick test without any problem

http://forums.x-plane.org/index.php?/forums/topic/104605-tu154-updates/

The tug is patiently waiting for a parking brake on (As it is already on). On, off, on, off, nothing happen. NWS was engaged.

**Comment by skiselkov** [comment]
I see what the problem (custom parking brake dataref). Should be easy to fix.

**Comment by skiselkov** [comment]
Can you test with `v0.32`? The plugin can't override the nose gear yet, you might need to disable the nose gear steering in the aircraft. Need to talk to Felis for that.

**Comment by birdydma** [comment]
Test done.

No turn. The  datarefs for NWS are:

sim/aircraft/gear/acf_nw_steerdeg1 (10, 65)
sim/aircraft/gear/acf_nw_steerdeg2 (10, 65)
sim/custom/SC/gear/tire_steer_command_deg, continuously from -65 to +65 or -10 to +10 (depend of the position of the NWS switch).

**Comment by birdydma** [comment]
Solved. Thanks you skiselkov and Félis.

**Comment by skiselkov** [comment]
I've still found some problems with the pushback stability, because BetterPushback was taking non-existent gears into account. Fix coming in a moment.

**Comment by skiselkov** [comment]
Please test with `0.33`. The pushback instability and side-to-side swaying should be gone.

**Comment by Igrok-kun** [comment]
I've tried just now. It said "Pushback failure. It seems aircraft does not have any steerable gears"

Tu-154 v 1.1.7
BP v 0.33

**Comment by skiselkov** [comment]
You need hydraulics on - the Felis aircraft is weird like that, it pretends the nose gear can't steer if the hydraulics aren't pressurized.

**Comment by Igrok-kun** [comment]
Ah, you are right. Now it works perfect, thanks.

**Comment by skiselkov** [comment]
I'll put in more detection code in the future to disable the steerability check on the Tu-154M. For now, I'll close this issue, since the incompatibility is resolved.
