### ISSUE TITLE
No tug skin

### ISSUE THREAD

**Issue by sjedd** [skiselkov/BetterPushbackC#57]
I installed ver .29 in the latest xplane 11.05r1 and I get the tug BUT it is all grey with no skin. I've installed a fresh copy of xplane 11 without any plugins except betterpushback and still get only grey tug.  Everything appeared fine when I was using ver. .16 of betterpushback. How can I return to ver. .16

**Comment by skiselkov** [comment]
Can you please post your `Log.txt`? If the tug is all grey, that could be a texturing problem, missing files or something. That will show up in the `Log.txt` file, so I need to see it to figure out what the problem might be.

**Comment by sjedd** [comment]
Yes, here is the log.txt
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1186169/Log.txt)

**Comment by sjedd** [comment]
I'm sorry, I meant to keep this issue open

**Comment by skiselkov** [comment]
Please check under `C:\X-Plane 11 new\Resources\plugins\BetterPushback\objects\tugs\AST-3F.tug\liveries\Swissport.livery`. You should be able to find the following file there: `AST-3F_tex.dds`. If it isn't there, you didn't extract BetterPushback correctly.

**Comment by sjedd** [comment]
Yes, I checked and that file IS there

**Comment by sjedd** [comment]
Here are two screenshots to show what it looks like.
![b738_2](https://user-images.githubusercontent.com/30581028/28781712-fcb3ba9e-75d8-11e7-9356-83b52d79d183.png)
![b738_3](https://user-images.githubusercontent.com/30581028/28781718-03a31cdc-75d9-11e7-94c5-e8a2b3977649.png)

**Comment by skiselkov** [comment]
Yep, that looks like a missing texture file. Can you please do a full listing of what files are under `objects/tugs/AST-3F/liveries`? Because it seems pieces of the plugin are missing and I don't know if you installed it wrong, or if it's all there and something else is causing the problem.

**Comment by sjedd** [comment]
As far as installation, I just place the whole BetterPushback folder into the Resources/Plugins folder. Under liveries there are 5 folders. generic.livery has AST-3F_lit.dds and AST-3F_tex.dds: GlobeGroundBerlin.livery has AST-3F_tex.dds and info.cfg; HAviationGroundServices.livery has AST-3F_tex.dds and info.cfg: LEOS.livery has the same 2 files and Swissport.livery also has the same 2 files.

**Comment by skiselkov** [comment]
I'll prepare a special debug version for you tomorrow with a lot more diagnostics enabled to hopefully help us narrow this down.

**Comment by cpuwolf** [comment]
why not try lastest verion v34?

**Comment by sjedd** [comment]
Did try ver. 0.34 and also the latest version 0.36. No change. Tug is still greyed out.

**Comment by sjedd** [comment]
Hopefully Skiselkov will provide the debug version and that will track it down.

**Comment by sjedd** [comment]
Skiselkov. I've been waiting for the special debug version you offered.  Have you been able to accomplish this yet?

**Comment by skiselkov** [comment]
@sjedd I'm sorry, kinda let this fall by the wayside, I'll stick more diagnostics into the next build coming tonight.

**Comment by skiselkov** [comment]
Can you please try the attached plugin? It contains additional debugging prints to figure out why the files apparently aren't readable.
[BetterPushback.zip](https://github.com/skiselkov/BetterPushbackC/files/1205660/BetterPushback.zip)

**Comment by sjedd** [comment]
I started at the same airport but problem actually happens at all airports. I've still got the greyed out tug. Here is the log.txt 
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1206283/Log.txt)

**Comment by sjedd** [comment]
I don't know if you've had a chance to look at the log.txt above. The main items that pertain to BetterPushback are 
2017-08-07 17:46:41 BetterPushback[tug.c:941]: Starting livery substitution for C:\X-Plane 11(2)\\Resources\plugins\BetterPushback\objects\tugs\AST-3F.tug\AST-3F.obj (liv: generic.livery)
2017-08-07 17:46:41 BetterPushback[tug.c:912]: DDS hit: TEXTURE AST-3F_tex.png -> C:\X-Plane 11(2)\\Resources\plugins\BetterPushback\objects\tugs\AST-3F.tug\liveries\generic.livery\AST-3F_tex.dds; attempting read check
2017-08-07 17:46:41 BetterPushback[tug.c:912]: DDS hit: TEXTURE_LIT AST-3F_lit.png -> C:\X-Plane 11(2)\\Resources\plugins\BetterPushback\objects\tugs\AST-3F.tug\liveries\generic.livery\AST-3F_lit.dds; attempting read check
2017-08-07 17:46:41 BetterPushback[tug.c:912]: DDS hit: TEXTURE_NORMAL AST-3F_norm.png -> C:\X-Plane 11(2)\\Resources\plugins\BetterPushback\objects\tugs\AST-3F.tug\liveries\generic.livery\AST-3F_norm.dds; attempting read check
Clean exit from threads.
0:02:19.507 E/SCN: Failed to find resource 'liveries/generic.livery/AST-3F_tex.png', referenced from file 'C:\X-Plane 11(2)//Resources/plugins/BetterPushback/objects/tugs/AST-3F.tug/'.

It failed to find the "liveries/generic.livery/AST-3F_tex.png"  I cannot locate this file. Where would it be?
