### ISSUE TITLE
Change language to english on non-national airports

### ISSUE THREAD

**Issue by Devirex** [skiselkov/BetterPushbackC#59]
I have selected german as X-Plane language and now the tug driver speaks german all the time, even if i am on an non german airport (Spain or France). Could it be changed to english in case that you are not on an german (or the laguage you have selected) airport?

**Comment by skiselkov** [comment]
Thanks for the request, I'm already working on this. Expect this to arrive soon.

**Comment by Devirex** [comment]
Thanks a lot for the quick reply. This fantastic plugin has got also great support.

**Comment by McDonne11** [comment]
And is it possible to add the subtitles?
For example:
Speech in native airport language
Text in your native language
It would be great!

**Comment by skiselkov** [comment]
@Devirex Feature has been implemented in v0.35. See release notes for details.
@McDonne11 I'll think about implementing it. Right now BP doesn't include any kind of text rendering facilities of its own, so it's not just a simple matter of flipping a few switches. Maybe as I get closer to a 1.0.

**Comment by Devirex** [comment]
Wow from native to accent to englisch, awesome!

**Comment by skiselkov** [comment]
Closing as complete.
