### ISSUE TITLE
Left click doesn't work

### ISSUE THREAD

**Issue by jakobeng1303** [skiselkov/BetterPushbackC#60]
v0.31 in the plugin directory
iMac 5k 10.12.6 Magic Trackpad 2
newest non beta Xp11 from steam (11.02 I think)
FF 763
I had this bug in the first couple of versions too but didn't have enough time to properly test because I was on holidays soon after but having arrived yesterday and dowloaded the newest version it still didn't work 

I'm unable to left click and therefore plan a push. Any ideas/suggestions? I can open the plugin and can click the buttons on the right side but oddly enough not on the rest of the screen to plan

**Comment by skiselkov** [comment]
Currently the click vs click-and-drag detection is rather primitive. It expects a click to take no longer than 0.2 seconds, otherwise it considers it a "click-and-drag" to reposition the view. If you are holding down the track pad for longer than 0.2 seconds, it will not detect as a click. As a temporary workaround until I get this fixed, can you try clicking quickly (so don't hold down the track pad, just do a quick push and release). In the next release I will fix this so it isn't so sensitive, as you're not the first I've seen having difficulty with this.

**Comment by jakobeng1303** [comment]
I'm currently inflight to KIAD but I will try and get back to you ASAP

**Comment by skiselkov** [comment]
Please test v0.33, clicking determination is no longer based on time, so it should allow you to slow-click on a track pad just as well.

**Comment by jakobeng1303** [comment]
I trief and the clicking works a lot better! Sadly it seems like the tug doesn't follow the path and it outputs the message that the pushback failed. Te route was plugged in correctly

**Comment by skiselkov** [comment]
I understand. Please attach your Log.txt and also please specify exactly what error it printed. Or if you can make a short video of the pushback to show me what happened, that would be even better.

**Comment by jakobeng1303** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1188341/Log.txt)
That's the log. I planned the route, pressed the the connect button, started to push via the dropdown menu which caused the plugin to ask me again for the path I want to go, then it started and just continued backwards without stopping. it didn't print any error (at least I didn't see anything) but it said pushback failed and that it'l disconnect (happened after I manually stopped it)

**Comment by jakobeng1303** [comment]
I'm unable to record it but I hope my description will help 1. plan in the layout 8works absolutely fine now!) 2. start, release brake, push starts 3. doesn't turn 4. push the stop button, set brake, truck leaves, I get the all clear sign and no warning anymore. I might have received the "failed push" because I set the brakes first before pushing the stop knob in the dropdown menu

**Comment by skiselkov** [comment]
I see you're flying on the 767. Do you have the latest update? Ramzzess released a fix for the non-turning pushback (it was an incompatibility in the plane).

**Comment by jakobeng1303** [comment]
latest version of the 767 or this plugin?

**Comment by skiselkov** [comment]
The aircraft, so the 767. Give me 15 minutes and I'll find which one should be the latest version (right now you're running version 1.1.28).

**Comment by jakobeng1303** [comment]
I stink it might be 1.1.32 or something along those lines. I'll just update it and get back to you

**Comment by skiselkov** [comment]
Just tested on 1.1.32 - turns just fine. You need to update.

**Comment by skiselkov** [comment]
Closing the click issue. Please open a new one if you're still having trouble turning in the 767 (though I suspect it has to do with your install not having the latest update).

**Comment by jakobeng1303** [comment]
thanks a lot! I love it and I was very surprised to see the great implementation in the 767!

**Comment by jakobeng1303** [comment]
Sorry, should have been posted yesterday but it seems like github thought differently..

**Comment by skiselkov** [comment]
No worries, glad I could help.
