### ISSUE TITLE
Feature request: Light for night pre-pushback

### ISSUE THREAD

**Issue by Igrok-kun** [skiselkov/BetterPushbackC#61]
Hello @skiselkov!

This is the situation I met yesterday in Oslo: https://s8.hostingkartinok.com/uploads/images/2017/07/d437f97df108e8c222603b89c5527315.png 

As you can see, there is no chance to find taxiway from such perspective in night time. Is it possible to make some kind of light near the cursor, which will helps to see the markings there?

Regards

**Comment by skiselkov** [comment]
Shouldn't be too hard to implement. Let me run some tests.

**Comment by skiselkov** [comment]
Done, will be coming out in next build.

**Comment by Igrok-kun** [comment]
Thanks!

**Comment by skiselkov** [comment]
Please test on v0.34.

**Comment by Igrok-kun** [comment]
Works awesome for me now: https://s8.hostingkartinok.com/uploads/images/2017/08/8ec11746d9d65494697da8f839b11d6e.png

Thanks!

**Comment by skiselkov** [comment]
Thanks for the feature suggestion!
