### ISSUE TITLE
PB Failure

### ISSUE THREAD

**Issue by alessandro61** [skiselkov/BetterPushbackC#62]
"error initialising audio message. Please reinstall PB"
New PB does not work.
Thanks.
Alessandro
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1196699/Log.txt)

**Comment by parshukov** [comment]
it is because Saso forgot to insert msg folder with audio files into the archive. You can take that folder from the previous release

**Comment by alessandro61** [comment]
Now it works.
Thank you and regards.
Alessandro

**Comment by skiselkov** [comment]
Ah sorry about this guys, new packaging script messed up. Will fix in a moment.

**Comment by skiselkov** [comment]
Fix is out in v0.36. That's what I get for making last minute changes without testing.

**Comment by skiselkov** [comment]
Closing as fixed for now. If it still happens in v0.36, please reopen.
