### ISSUE TITLE
No sound V0.36

### ISSUE THREAD

**Issue by Pilotwillem** [skiselkov/BetterPushbackC#66]
No sound with B CRJ200

**Comment by skiselkov** [comment]
*Always* attach a `Log.txt` when you're having trouble. Also, can you be a bit more specific about "no sound"? No tractor sounds? No ground crew audio? Did you check that you don't have the exterior and radio volume turned down in X-Plane?

**Comment by Pilotwillem** [comment]
issue solved. x-plane set the audio preference back to zero. i don't know why. 
compliments for plugin. it wonderfull.

**Comment by skiselkov** [comment]
Glad to hear you got it sorted, closing this issue now.
