### ISSUE TITLE
Muffle Sound in Flight Deck

### ISSUE THREAD

**Issue by AlexJohn73** [skiselkov/BetterPushbackC#67]
I find the sounds to be a tad loud in the flight deck. Would it be possible to sort of muffle these sounds, so that the pushback tug is quieter, and cut the treble? Excellent plugin nonetheless.

**Comment by skiselkov** [comment]
Thanks for the feature request. I'll implement a volume slider in the Preferences and switch to a low-pass-filtered sound set when in the cockpit.

**Comment by AlexJohn73** [comment]
Thanks for the quick reply. That is exactly what I'm after - I can't wait to see what else this plugin has to offer.

**Comment by skiselkov** [comment]
Feature implemented in v0.39. Internal audio now follows "Interior volume" slider in X-Plane 11, allowing you to control its loudness separately. The inside sounds have also been passed through a low-band EQ, so the sounds are more bassy. Opening a window will result in a gradual transition from internal sounds & volume to external and vice-versa.

**Comment by AlexJohn73** [comment]
Thanks. I'll take a look tomorrow.

**Comment by AlexJohn73** [comment]
It's a little louder than I would have thought it would be, but I can live with it, particularly when you have all the fans and A/C systems running (in Boeing especially). Thanks for adding it!
