### ISSUE TITLE
Texture resolution for liveries

### ISSUE THREAD

**Issue by nriddell** [skiselkov/BetterPushbackC#68]
I've noticed that the texel density is inconsistent on the current liveries that have been added to the plugin resulting in low resolution textures in certain areas. Would you be able to provide the high poly mesh (if available) to allow a new UV unwrap and bake to enable consistent resolution across the whole map. 

Happy to help

**Comment by skiselkov** [comment]
Unfortunately, there is no high-poly mesh. What's in the blender files is all that I have. I'm aware that the unwrap isn't exactly pro (my first project where I had to make 3D models), so I'd be happy for any help. However, given that this would trash all existing texturing work, I'm somewhat hesitant to commit to it.

**Comment by skiselkov** [comment]
Closing due to lack of movement. Reopen if you'd like to work on continue with this.
