### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ftd1949** [skiselkov/BetterPushbackC#7]
Nice but definitely some bugs. If you go to XP Menu, Flight, Flight Configuration, It won't let you stop the module without crashing XP.
Hope you can get it to work with Zebo.  Would there be anyway to bind it to a button or key to initiate pushback?
Thanks so much !

Fantastic plugin.

**Comment by skiselkov** [comment]
Closing as duplicate of #2. This is a known issue and will be addressed shortly.
