### ISSUE TITLE
Unable to see BetterPushback in XP11 plugin menu

### ISSUE THREAD

**Issue by Braggerblock** [skiselkov/BetterPushbackC#72]
Have tried various versions (also pre-releases). The plugin does neither appear in the XP11 plugin menu nor in the plugin admin section. Have installed into the correct folder /resources/plugins. Am unable to use it.

**Comment by zasavage** [comment]
Could be that you have a folder in a folder , make sure that the folders are . /resources/plugins/BetterPushback/( 32 and 64 folders  etc  here )

**Comment by Braggerblock** [comment]
mmm, the path is correct (no folder in folder) but the 32 and 64 folders are missing. Have I downloaded the wrong zip-file? The unpacked  zip-file does not contain these two folders.

![grafik](https://user-images.githubusercontent.com/30768584/29002028-3e981fd0-7a99-11e7-8d62-5d90c9519961.png)

**Comment by skiselkov** [comment]
You have downloaded the source code ZIP. That's not what you want. You want
the first ZIP file labeled "BetterPushback.zip". Ignore the ones with
"source code" in the name.

**Comment by Braggerblock** [comment]
Ok, thanks for helping out. All ok now.
