### ISSUE TITLE
Nominal financial recompense....?

### ISSUE THREAD

**Issue by JLSeagull** [skiselkov/BetterPushbackC#74]
Perhaps I am guilty of missing something about the workings of GitHub - or perhaps you are simply one of those extra-ordinary people who willingly devote your free-time and creative talents for the benefit of others....
Whatever; Would it be too implausible to suggest making this superb add-on, at the the very least, donationware?

**Comment by skiselkov** [comment]
Don't worry, you're not missing anything. I'm not taking donations at this time. Maybe in the future when the plugin is closer to a 1.0 release. Thanks for offering to support me, I greatly appreciate the enthusiasm!
