### ISSUE TITLE
No portuguese voice

### ISSUE THREAD

**Issue by tubarao2007** [skiselkov/BetterPushbackC#75]

**Comment by tubarao2007** [comment]
I think the problem is on zibomod, not here.
But I still no portuguese voice. Spanish is ok.

**Comment by skiselkov** [comment]
There is currently no plain Portuguese voice localization available, only Brazilian Portuguese, which you will hear when flying in Brazil.

**Comment by tubarao2007** [comment]
Yes, I mean brazilian portuguese!!! But, I put to B. portuguese in all airports and I'm still listening english.

**Comment by skiselkov** [comment]
This is expected behavior. The language selector on the left means "plain Portuguese", not "Brazilian Portuguese". There is currently no method implemented for selecting a nationally-flavored branch of a language.

**Comment by skiselkov** [comment]
Closing this for now. Pending availability of a generic Portuguese audio, there's not much else I can do.
