### ISSUE TITLE
Deactivate plugin during "in air"

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#77]
a minor thing: you should deactivate the plugin while the aircraft is in the air. The current message is a bit irritating. 
cheers and great work!!

**Comment by skiselkov** [comment]
> The current message is a bit irritating.

Thanks for the bugreport. Can you please be a bit more specific about which message is irritating?

**Comment by skiselkov** [comment]
I've done some testing, and the message that the plugin produces during flight is somewhat cryptic (talking about not having steerable gears). I've reworked it a little to say that the aircraft isn't on the ground. Sound good to you?

**Comment by xplana** [comment]
Hey Soso,

this ist exactly what i meant. 
Its nothing major but completes a great piece of software!
Thanks and great job sir!

Wilhelm


Am 07.08.2017 um 18:13 schrieb Saso Kiselkov <notifications@github.com>:

**Comment by skiselkov** [comment]
Well then good news, fix is out in v0.39. Please test.

**Comment by xplana** [comment]
i will
thank you

**Comment by xplana** [comment]
perfect
