### ISSUE TITLE
You may start engines

### ISSUE THREAD

**Issue by birdydma** [skiselkov/BetterPushbackC#79]
Good day Saso,

When engines are already running, can you sweep this message?

**Comment by skiselkov** [comment]
Yeah, both this and not calling for setting the parking brake on ready2conn will need to be chomped out of the voice messages and placed into separate audio files. Should have done this from the start. I'll get to it, hopefully today or tomorrow.

**Comment by skiselkov** [comment]
Will be addressed in next build tonight. Coincidentally, I need a new version of `ready2conn.wav` **without** the "set parking brake" at the end. Everything else in the message is ok, just stop before asking for the parking brake. I tried to modify the original sound file, but the words are little too close together and it would sound weird if I just cut you off there.

**Comment by skiselkov** [comment]
Most audio fixed in v0.40 to not requested parking brake or clear engine start if brake is already set or engines are already running. I need some more audio messages that were just too tight to cut properly without making it sound odd. Please also check if I guessed correctly where to cut the French audio.

**Comment by birdydma** [comment]
0.40 tested (Xp 11, stock B 58, engines running).

No more "You may start engines, but always "Release parking brake" as it is already on.

More to come this afternoon with new commands and smartco.

**Comment by skiselkov** [comment]
Closing this now. I'll address the smartcopilot features in a separate bug.
