### ISSUE TITLE
Jardesign A320 Nosewheel bug

### ISSUE THREAD

**Issue by BFaguha** [skiselkov/BetterPushbackC#8]
When the tug have the nosewheel in place and locked the nosewheel texture overlap the pushback tug.

i took a picture:
![pushback bug](https://user-images.githubusercontent.com/30203459/28242907-5b7aeae6-69b0-11e7-8d39-9e6fb93f13ba.png)

**Comment by skiselkov** [comment]
Can you describe this in some more detail? I don't have the aircraft, so I'm going to have to guess at what's wrong. Like, does the problem exist *while* the tug is driving up, or only once it "attaches"? Do you have any other plugins that might affect rendering? (like xEnviro, SkyMaxxPro, etc.) If possible, please make a video of this effect, so I can see it happening live. Any little bit of information would help.

**Comment by BFaguha** [comment]
Thank you for your reply so quickly! and i´m sorry for little information; It happens as soon the tug get closer to the gear. The plugins i have: Autogate, Flywithlua, X-life, xgs, and 124thATC64 (that i almost never use). I´m going to upload a video on Youtube and post the link here. I´ll be right back.

**Comment by BFaguha** [comment]
https://www.youtube.com/watch?v=Ph5ErmntLqI&feature=youtu.be

**Comment by weslley-pereira** [comment]
I had no problems here.

This bug you are receiving you are viewing through the "Forward with 3-D Panel" mode.

This is also true of the Ground Handling seen by the Forward with 3-D Panel.

**Comment by skiselkov** [comment]
I have a bit of an idea that might work around this. I've attached an experimental version of the plugin for you to test. Please try it out and let me know if it solves this issue with the JARbus A320.
Note: this build is Windows-only. Let me know if you need a Mac/Linux build.
[BetterPushback-experimental.zip](https://github.com/skiselkov/BetterPushbackC/files/1150794/BetterPushback-experimental.zip)

**Comment by skiselkov** [comment]
@weslley-pereira Oh, I didn't know that @BFaguha was using the 3D cockpit view. @BFaguha can you confirm that? If so, please use a proper external view (such as chase view or free view), otherwise external object rendering is always going to look screwed up.

**Comment by BFaguha** [comment]
@skiselkov good morning,
Yes i´m using 3D Cockpit View (i´m using it a lot more than free view). I tried with normal external views and it´s perfect. So the problem was 3D Cockpit View and i didn´t know that, i´m sorry. Problem resolved. So, i didn´t tried your build. I just won´t use 3D Cockpit View to check my plane outside. Thank you very much for your help and for creating this excellent plugin. Thank you. Bruno Fagulha.

**Comment by skiselkov** [comment]
No worries, glad we could get this resolved.
