### ISSUE TITLE
Pause pushback process via brake application doesn't work

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#80]
Hi Saso,

sometimes there is a need to be able to pause (and continue) the pushback - often because Ground Control requests this (mostly because of traffic).

If i choose a long route (pushback plan) lets say from a parking position to a remote hangar, sometimes you have to cross junctions or runways where you also have to stop if ATC requests this and continue if you are requested to do so. 

I would like to ask you to think about simple Pause/Continue button(s) in order to be able to halt and continue the process. 

Find attached a picture with one of the described situations and how such buttons could look lik. 
Thank you

![bildschirmfoto 2017-08-08 um 14 41 42](https://user-images.githubusercontent.com/17392829/29072452-f4fbf33c-7c47-11e7-8855-6a513eb84536.png)

**Comment by birdydma** [comment]
Parking brake on during the pushback?

**Comment by xplana** [comment]
:-) its working well
sorry, completely missed this

**Comment by skiselkov** [comment]
@birdydma Thanks for helping out.
@xplana As @birdydma said, one way to do it is to apply the parking brake. However, this can be pretty intense and even tip the aircraft onto its tail. To slow down more gradually, you can gently depress the brakes to bring the aircraft to a gradual stop. BP monitors brake pedal application and if it goes beyond 10%, BP will stop attempting to push the aircraft. As soon as you release the brakes, BP continues.

**Comment by xplana** [comment]
great!

**Comment by skiselkov** [comment]
Actually there's a bug in stopping it using the normal brakes. Will fix.

**Comment by skiselkov** [comment]
Please try v0.40, it should respond to pedal brake application by pausing pushback.

**Comment by xplana** [comment]
Brilliant
