### ISSUE TITLE
Embraer 110 - Bandeirantes not working properly

### ISSUE THREAD

**Issue by parshukov** [skiselkov/BetterPushbackC#81]
Hi! 
When I try to use a pushback service the aircraft at the moment of connecting the toe starts to go back. I noticed that it happens when plugin overrides wheel steer (change dataref to 1) and after the dataref (nosewheel_speed) increases up to "-12" and the back to 0.

**Comment by skiselkov** [comment]
Can you please record a video of this? That would really help me? I don't have the EMB110, so I can't test it myself.

**Comment by McDonne11** [comment]
At the request of N.Parshukov, here is a link to the video with this problem:
https://youtu.be/1uv3iOT9ltk

**Comment by skiselkov** [comment]
I'm sorry, but I can't see what the problem is. In the video it looks like the pushback was successful.

**Comment by parshukov** [comment]
https://youtu.be/lpkSUfjzFhE

here it is

**Comment by skiselkov** [comment]
Can you check that you don't have one of your brake pedals applied a little? The datarefs for the brake pedals have `brake_ratio` in their name (`sim/cockpit2/controls/left_brake_ratio` and `sim/cockpit2/controls/left_brake_ratio`). Both of these datarefs must be `0` - if not, I've seen X-Plane's physics model go a little crazy when trying to push the aircraft.
If the problem still persists, can you make video of the **full** pushback procedure while having the `brake_ratio` dataref displayed? I suspect they jitter around a non-zero value.

**Comment by parshukov** [comment]
ok, I will figure this out tomorrow. if it is the problem in dataref, I will make a patch for it)

**Comment by skiselkov** [comment]
No, I mean I think the problem might be in your physical brake pedals - I suspect they are giving a non-zero brake value even when not depressed. But I will investigate this a little bit more, I'm not 100% sure yet.

**Comment by parshukov** [comment]
oh, but I have not any pedals)

**Comment by parshukov** [comment]
I've checked - it is strange but yes - the left and right brake ratio become nonzero during the pushback process. and it happens every time in the different time)

**Comment by parshukov** [comment]
moreover I tried to manually add a piece of code to lua to make these datarefs always be 0 - but it is not work  - I guess bp is overwriting it at all...

**Comment by birdydma** [comment]
Good day Nick,
I have not the Embraer, may be you have not the Saab, but have o look here:
https://github.com/skiselkov/BetterPushbackC/issues/17

Can you see something similar with your issue?

**Comment by parshukov** [comment]
hi. yep, it is the same...

**Comment by birdydma** [comment]
Can you test BP with your AN 24?

XP 10 of course, engines not running, The tug have hard time to do a turn.

**Comment by parshukov** [comment]
@birdydma what do you mean by "hard time"? can you record a video?)

**Comment by birdydma** [comment]
Starting the turn the speed is going very slow, and the push stops after 1 or 2 meters (the leg is much more long).

**Comment by parshukov** [comment]
@birdydma can you send me here a screenshot of the prefs of the An24?

**Comment by birdydma** [comment]
Prefs? Joystick, rendering?

**Comment by parshukov** [comment]
@birdydma no, prefs of An - I mean An settings from the left aircraft menu. I lost my PC some time ago and now I have a notebook with 5fps in sim, it is very difficult to check the aircraft)

**Comment by birdydma** [comment]
![2017-08-09_16h52_44](https://user-images.githubusercontent.com/30256581/29128133-4d1bb0d0-7d23-11e7-8183-69045fccbcd3.jpg)

**Comment by birdydma** [comment]
Works with the NWS switch in the middle position, even cold and dark. Nice.
![2017-08-09_17h22_11](https://user-images.githubusercontent.com/30256581/29129856-78c557ae-7d28-11e7-99dd-822f0c40f73b.jpg)

**Comment by parshukov** [comment]
super

**Comment by parshukov** [comment]
@skiselkov Saso, any advises?)

**Comment by skiselkov** [comment]
So far no ideas. BP does set your brakes when it is connecting & disconnecting, but never during towing. I might need to get the EMB110 to test it myself. I'll keep you posted.

**Comment by birdydma** [comment]
Hi,,
May be it's time to think differently with those birds. 
For exemple, the pushback speed is slowing down with the Saab: 
Could it be something related to beta mode (position of CL, throttle lever, stock datarefs overriden by SASL or Gizmo)

**Comment by parshukov** [comment]
@skiselkov Saso, during pushback everything is ok, the magic happens when it is connecting and disconnecting. And during that I can't set my left and right brakes to 0..maybe you can add a couple of strings in your code to check if it is Emb100 to not controls brakes? and I will add an ifthenelse for bp during operation to set it to 0?

**Comment by birdydma** [comment]
The new logic solve the problem for the Saab.  The Nikolay's AN 24 is also correctly pushed.

What about your Brazilian bird?

**Comment by parshukov** [comment]
@birdydma  will check now :) An24 Parshukov Edition had no problems as I know)))

**Comment by parshukov** [comment]
yep! It seems everything is ok now!

**Comment by skiselkov** [comment]
Thanks for the update, closing.
