### ISSUE TITLE
no voice language change v0.39

### ISSUE THREAD

**Issue by AirLuSa** [skiselkov/BetterPushbackC#82]
Since version 0.39 I am not able to change the voice language for the airpots. Always (standard) english is played, regardless, which option is set in the preferences.

Best regards
Lukas

**Comment by skiselkov** [comment]
Thanks for the bug report, will check.

**Comment by skiselkov** [comment]
Can you please attach this file from your simulator: `Output/preferences/BetterPushback.cfg`. I want to check what preferences BetterPushback is using.

**Comment by AirLuSa** [comment]
okay here it is

[BetterPushback.cfg.zip](https://github.com/skiselkov/BetterPushbackC/files/1209474/BetterPushback.cfg.zip)

**Comment by skiselkov** [comment]
You have your language preferences set to "always use English". You need to select the second option under "Ground crew audio". See attached image.
![shot](https://user-images.githubusercontent.com/3300688/29093640-cf56437e-7c8a-11e7-97a6-f01fdb07f55f.png)

**Comment by AirLuSa** [comment]
Mhm..  Thought that if I choose english at all airports, BP plays the en-de audio set files at EDDL for example, but instead it plays the standard english sound set. So maybe it's my mistake..

**Comment by skiselkov** [comment]
Let me investigate. I'm fairly certain it should work the way you describe, so there might still be a bug there.

**Comment by skiselkov** [comment]
I've found the bug, build with fix coming shortly.

**Comment by skiselkov** [comment]
Should be fixed in v0.40.

**Comment by AirLuSa** [comment]
fixed
