### ISSUE TITLE
problem with changing audio language 0.39

### ISSUE THREAD

**Issue by mariuo** [skiselkov/BetterPushbackC#83]
Hello,
i have a issue, when is set Português Audio and the option "My Language at all airport", just work only some brazillian airports... this is option is to setup português audio for all airports... Ex: SCEL the audio change to english.

thanks

**Comment by skiselkov** [comment]
Yes, this is a known issue right now because we don't have "generic" Portuguese audio, only Brazilian Portuguese. Would you be willing to record the generic sound set? I can then add it and it will be used for Portuguese users outside of Brazil.

**Comment by mariuo** [comment]
May i suggest for one option with Portuguese Brazilian audio generic, there are to many brazilian pilots use your plugin, i dont have portuguese speaking from Portugal for recording to help you, i'm sorry.

Thanks and congrats for the plugin

**Comment by jorgeuvo** [comment]
@skiselkov I agree with @mariuo to make the Brazilian Portuguese as generic Portuguese as well,     while we don't have the correct audio.

I will try a Portuguese friend to create the generic audio. I will be back soon to you

**Comment by jorgeuvo** [comment]
@skiselkov I talked with José Almeida and he will join the other post for the Generic Portuguese audio.

**Comment by JoseBDA** [comment]
The Generic Potuguese audio has been uploaded and I expect it will be in the next release

**Comment by skiselkov** [comment]
@JoseBDA Yep, I just need to finish the audio master, but it should be coming out in a few hours. I'm also working on a major update to the driving logic, which is why this is taking so long.

**Comment by skiselkov** [comment]
Implemented European Portuguese audio in v0.42. Please test.

**Comment by skiselkov** [comment]
Closing as implemented.
