### ISSUE TITLE
Random 10-30 Second Delay Between Movements

### ISSUE THREAD

**Issue by AlexJohn73** [skiselkov/BetterPushbackC#84]
Hello, me again. When the tug needs to pushback and _then_ tow forward (or the other way around), it switches between the two instantly, which I think is a bit unrealistic.
Would it be possible to add a random (or fixed) 10-30 second delay to simulate the time it would take for the driver to turn around, put it in gear etc.?

**Comment by skiselkov** [comment]
Not a bad idea, but I'd definitely make the delay much shorter. For one thing, these vehicles all have automatic transmissions, so reversing direction takes about as long as it takes for you to pull a lever and move your foot from the brake to the accelerator.

**Comment by skiselkov** [comment]
Feature implemented in v0.40 as a 2-3 second delay when turning around. I feel that any more would become annoying to users.

**Comment by skiselkov** [comment]
Closing this as implemented.
