### ISSUE TITLE
New icons and outside view

### ISSUE THREAD

**Issue by birdydma** [skiselkov/BetterPushbackC#86]
I can get the new icons only if i stay in the cockpit. When MAJ/8 is applied, they are not displayed.

**Comment by AirLuSa** [comment]
for me in the cockpit they look like this: 
![bildschirmfoto 2017-08-09 um 12 31 51](https://user-images.githubusercontent.com/30418648/29117554-ea31a11a-7cfe-11e7-974d-8c7b221b877d.png)

**Comment by birdydma** [comment]
It's a riddle.

PS: My OS is Win 10.

**Comment by skiselkov** [comment]
Interesting, but I think I might have an idea what's wrong. What is `MAJ/8`?

**Comment by skiselkov** [comment]
Can you give this file a try? Simply replace `64/win.xpl` with it. Let me know if you need a build of this for another platform (Mac/Linux).
[win.xpl.zip](https://github.com/skiselkov/BetterPushbackC/files/1211243/win.xpl.zip)

**Comment by AirLuSa** [comment]
Yes please compile for mac. Then I can check it.

**Comment by skiselkov** [comment]
Attached.
[mac.xpl.zip](https://github.com/skiselkov/BetterPushbackC/files/1211251/mac.xpl.zip)

**Comment by birdydma** [comment]
MAJ + 8 (8 on the top of the keyboard): outside view. In fact, not 8 but - 

My bad.

**Comment by skiselkov** [comment]
Ah, gotcha, I understand now what you mean. Source of the confusion: everywhere else in the world, that key is called "Shift", not "Maj". Anyway, please test if the modules above fix the problem. If so, I can have a full build ready in an hour.

**Comment by birdydma** [comment]
Solved for Win 10.

Also tested the new BetterPushback/reconnect. The job is done, but without any vocal messages.

**Comment by skiselkov** [comment]
@birdydma Thank you.
> Also tested the new BetterPushback/reconnect. The job is done, but without any vocal messages.

Are you talking about smartcopilot syncing the command to the slave?

**Comment by AirLuSa** [comment]
seems to work now on Mac

**Comment by skiselkov** [comment]
Thanks, fix in next build tonight.

**Comment by skiselkov** [comment]
Fixed in build v0.41. Please test.

**Comment by birdydma** [comment]
Fixed.

**Comment by skiselkov** [comment]
Thanks for testing.
