### ISSUE TITLE
Wheel contact points and aircraft shape

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#87]
Sasho,

if the trucks pulls the aircraft into a parking position, currently it does not seems to be possible to exactly place the aircrafts nosegear on to a required aircraft specific marking. Please see the attached airport picture for this where there are different spots for the airbus and Boeing models.  

It would be good to be able to see the gear contact points (at least of the nose gear) in the pushback planning mode (please see second attached picture) and be able to precisely place the aircraft according to its nosegear contact point. w

It would also be good to generate (if somehow possible) the shape of the aircraft and to make sure the shape corresponds with the aircraft size. (Ok, this one is really just in case you are getting bored during the winter :)

Thank you.
![bildschirmfoto 2017-08-09 um 12 36 27](https://user-images.githubusercontent.com/17392829/29118210-4adcc8d0-7d01-11e7-95bc-757cd633a365.png)
![529649523](https://user-images.githubusercontent.com/17392829/29118211-4b06d350-7d01-11e7-87f8-8cadb09286d5.jpg)

**Comment by skiselkov** [comment]
Nice idea on the landing gear spots, will be in the next, as well as some refinements to the driving algorithm to make it more accurate. The exact replica of the aircraft is something I have considered, but it's exceptionally difficult to try and pull the aircraft out of x-plane (short of manually rendering the model I can't think of an obvious way). I might implement a library of aircraft overlay images, but as you said, that's a project for long winter nights.

**Comment by skiselkov** [comment]
Implemented in v0.41, please test.

**Comment by xplana** [comment]
hey sasho,

did some quick tests and it looks good - it is working perfect with the default Boeing 737, Rotate MD80, default King Air. 

![bildschirmfoto 2017-08-09 um 22 34 12](https://user-images.githubusercontent.com/17392829/29142726-1af0e71c-7d53-11e7-949e-d11e709de963.png)

![bildschirmfoto 2017-08-09 um 22 56 02](https://user-images.githubusercontent.com/17392829/29144323-d0db23b2-7d58-11e7-8f57-7d6026614ce0.png)

![bildschirmfoto 2017-08-09 um 23 16 02](https://user-images.githubusercontent.com/17392829/29144324-d102ba80-7d58-11e7-9576-9679a71779e7.png)

The bad news, the IXEG 737 is not yet working as it should. 4 out of 5 trials went wrong.  The tug pulled the aircraft a bit too much. 1 trial succeeded. 

![bildschirmfoto 2017-08-09 um 22 21 36](https://user-images.githubusercontent.com/17392829/29142833-775fc626-7d53-11e7-9ed6-802d405b59f9.png)

what exactly does the green line in front and the red line behind the aircraft icon in planning mode stand for?

Thanks and great work!

**Comment by skiselkov** [comment]
> The bad news, the IXEG 737 is not yet working as it should. 4 out of 5 trials went wrong. The tug pulled the aircraft a bit too much. 1 trial succeeded.

The algorithm does have a bit of imprecision so far. I'll see if I can tighten it up so more.

> what exactly does the green line in front and the red line behind the aircraft icon in planning mode stand for?

It's just an extended aircraft centerline to help you align the aircraft exactly with the taxiway. It only appears when planning forward motion, or when pushing and the last portion of the push is a turn (to show you that there is no straight push section). The same goes for the red line that extends behind the aircraft (except the rules are reversed, i.e. only shows when pushing, or when towing and last segment is a turn).

**Comment by xplana** [comment]
Saso,
Any chance that the wingspan of your aircraft icon gets the wingspan from the aircraft in x-plane and maybe tha aircraft length? That would be a good representation. I see that the entire shape is quite a difficult thing to do. 
Cheers

**Comment by skiselkov** [comment]
I have a test module that you try. Just place this into the plugin under the "64" folder, replacing the old one that's there. This is currently Windows-only. Let me know if you need another platform. With this version, I'm able to get the IXEG and any other aircraft pretty much to within an inch or two of where I want it to be.
[win.xpl.zip](https://github.com/skiselkov/BetterPushbackC/files/1216120/win.xpl.zip)

**Comment by xplana** [comment]
Hi saso,
I am on a mac

**Comment by skiselkov** [comment]
Mac build is attached:
[mac.xpl.zip](https://github.com/skiselkov/BetterPushbackC/files/1216702/mac.xpl.zip)

**Comment by xplana** [comment]
thanks. I´ve tested a couple of times and it looks very good, see here: 
![bildschirmfoto 2017-08-11 um 09 32 14](https://user-images.githubusercontent.com/17392829/29204779-4088b050-7e79-11e7-867f-1b81706c921d.png)
![bildschirmfoto 2017-08-11 um 09 38 01](https://user-images.githubusercontent.com/17392829/29204780-40b20f0e-7e79-11e7-9c8d-2fd87ddfc90d.png)

**Comment by xplana** [comment]
actually after some more tests, one single test failed. The aircraft was towed way too much. It was supposed to be parked on the first marking, please see where it was towed.  
As i said, this was the single test that failed. I have no idea what could have triggered that. 
Cheers

![bildschirmfoto 2017-08-11 um 10 18 21](https://user-images.githubusercontent.com/17392829/29205979-184e40e4-7e80-11e7-80d5-adb9255d3587.png)

**Comment by skiselkov** [comment]
I'm working on a major update to the steering logic. Maybe that will help resolve this. But even with the code as-is, I couldn't reproduce the problem you're having, so maybe it's just something on your end... You did make sure to give the tug enough room to straighten out, right? So you didn't just come right out of a turn and expect the nosewheel to land on the dot?

**Comment by xplana** [comment]
yes, there was plenty of room and the tug just passed a long straight line, no curves close to the dot where the nose wheel was supposed to land. 
I´ll close this, as the main issue is solved.
