### ISSUE TITLE
Nosewheel still turning while pushback

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#90]
Hi sasho,
as you can see in this video, the aircrafts nose wheel is still turning while lifted by the tug. 

[https://www.youtube.com/watch?v=DOixWaM6_F0&feature=youtu.be](url)

Any chance to stop it turning or is this some x-plane accessibility problem?

Thanks

**Comment by skiselkov** [comment]
Thanks for the bugreport. Yes, this is a limitation of the X-Plane API. At the moment I have no way of stopping the nosewheel animation when repositioning the aircraft. I'm talking to Laminar to try and figure out a way to get this solved at least on XP11 (XP10 is likely never going to get rid of this).
