### ISSUE TITLE
Vienna Airport Livery AST-3F

### ISSUE THREAD

**Issue by liebbe10** [skiselkov/BetterPushbackC#94]
I made a livery for LOWW Vienna International Airport
![capture](https://user-images.githubusercontent.com/30324171/29182881-e2d8d1c4-7e00-11e7-98e5-45b639bb7c28.PNG)
[WienSchwechat.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1215777/WienSchwechat.livery.zip)

**Comment by skiselkov** [comment]
Thanks for the livery! I'll include it in the next build.

**Comment by skiselkov** [comment]
Included in v0.42.

**Comment by fregate083** [comment]
Hi,
At LOWW, I have following bugs (see photo) :
-a kind of black rectangle under the tug engine
-window are not transparent but opaque grey

Xplane 10.51 r1 and JAR DESIGN 2.7
![loww bp](https://user-images.githubusercontent.com/30977163/29306570-9249ab88-819e-11e7-884a-b77855356f4a.jpg)

**Comment by liebbe10** [comment]
And the windows aren't transparent... I had this bug while creating the livery when I exported it as a png file...

**Comment by fregate083** [comment]
Ok thanks a lot.
But what can I do to make things better ? Especially with this black rectangle  ?

regards

Alexandre

**Comment by liebbe10** [comment]
Sorry no idea... Skiselkov has to awsner,  if it is due to the plugin or the livery...

**Comment by fregate083** [comment]
ok thanks for your help.

Do I have to repost my question elsewhere for Skiselkov ? Or to wait here for his answer ?

Thanks

**Comment by liebbe10** [comment]
Maybe you should open a new issue as this one is closed

**Comment by skiselkov** [comment]
No worries dude, I see updates on all issues, regardless of their state, but occasionally I do need to sleep a little :)
