### ISSUE TITLE
New vehicles?

### ISSUE THREAD

**Issue by NathanCG2** [skiselkov/BetterPushbackC#95]
Are you thinking of making other vehicles in the future as catering, loaders?

**Comment by skiselkov** [comment]
Thanks for the suggestion. Not really at the moment, however. I don't want to duplicate the functionality of plugins such as Ground Handling Deluxe, which are doing a fine job and I don't think I'd have much new to add there. I'll keep it in mind for a 2.0 or 3.0 version though.
