### ISSUE TITLE
Single engine aircraft and engine running

### ISSUE THREAD

**Issue by birdydma** [skiselkov/BetterPushbackC#97]
There is no request: Stop engine first. 

Hopefully, i am not a tug driver but a pilot.

**Comment by skiselkov** [comment]
Will implement, but only via an error message when hitting "start pushback", not via an audio message (too much work for too much user stupidity).

**Comment by birdydma** [comment]
Now a new one:

The silly driver say: You may start engines!

**Comment by skiselkov** [comment]
Which aircraft are you testing and XP10 or XP11?

**Comment by birdydma** [comment]
XP 11 and the stock Cessna.

**Comment by birdydma** [comment]
I don't see any commit about this one, but it is fixed with the 0.43 release.

**Comment by skiselkov** [comment]
Thanks for testing, I forgot to put it into the release notes. Closing.
